.npmrc, README.md, package-lock.json, package.json, src/stories/footer/Footer.tsx, src/stories/footer/FooterColumn.tsx, src/styles/scss/shared.scss
This improves the accessibility of the footer based on experiences when integrating the design system with https://github.com/danskernesdigitalebibliotek/dpl-cms/ and analysing a demo page with pa11y.
This reports the following errors:
```
• Heading levels should only increase by one
(https://dequeuniversity.com/rules/axe/4.3/heading-order?application=axeAPI)
(html > body > div > div > div:nth-child(4) > div:nth-child(2) > div >
div:nth-child(2) > div:nth-child(1) > h4)
<h4 class="text-header-h4 mb-16">Åbningstider</h4>
• All page content should be contained by landmarks
(https://dequeuniversity.com/rules/axe/4.3/region?application=axeAPI)
(html > body > div > div > div:nth-child(4) > div:nth-child(2))
<div class="footer--desktop"> <div class="pagefold-paren...</div>
```
Also improve …
=> Improve footer accessibility

base.scss, src/stories/checkbox/Checkbox.stories.tsx, src/stories/dropdown/Dropdown.stories.tsx, src/stories/dropdown/Dropdown.tsx, src/stories/dropdown/dropdown.scss, src/stories/footer/Footer.tsx, src/stories/list-details/ListDetails.stories.tsx, src/stories/list-details/ListDetails.tsx, src/stories/list-materials/ListMaterials.stories.tsx, src/stories/material-banner/MaterialBanner.tsx, src/stories/material-banner/material-banner.scss, src/stories/material-card/MaterialCard.stories.tsx, src/stories/modal-pause/ModalPause.stories.tsx, src/stories/modal-pause/ModalPause.tsx, src/stories/modal-pause/modal-pause.scss, src/stories/modal-search/ModalSearch.stories.tsx, src/stories/modal-search/ModalSearch.tsx, src/stories/modal-text/ModalText.stories.tsx, src/stories/modal-text/ModalText.tsx
This PR includes some changes/fixes for some of the components in dpl-design-system
- Removed props from Modal Search since they were not used for anything
- Add possibility for changing the text in the "Text Modal" in storybook
- Fix position error with link-filters in Material Banner/Modal Details
- Add option to choose icons on dropdown, since it should be able to change between two icons
- Create new component "Modal-pause" since it was missing
- Disable controls in checkbox and materialCard, since we can't get the states to work with controls in SB. The only help to find on the internet is to make states work with "Actions" - not "Controls".
- Add datepicker input to ModalPause component
The error with Chromatic is not from this PR. I have built the storybook locally and reviewed the …
=> DDF feedback fixes

README.md
This is somewhat duplicates what is already available in the GitHub
documentation but what scopes are actually required is not documented
and it can be handy to also have the direct link with the scopes 
handy.
=> Document process for authenticating when using the NPM package

src/stories/material/Material.stories.tsx, src/stories/material/Material.tsx
This PR is to make sure that the dpl-react and dpl-design system are as similar as possible.
This change contains
- Adds the same logic as used in dpl-react to determine if it is a tag or a span image to display in 
- Change the storybook to have the right props and setup
=> Change material cover render

base.scss, public/icons/basic/icon-select-arrow.svg, src/stories/material-app/material-app.scss, src/stories/material-app/material-app.stories.tsx, src/stories/material-app/material-app.tsx, src/stories/material-header/material-header-text.tsx, src/stories/material-header/material-header.scss, src/stories/material-header/material-header.tsx, src/stories/material-header/material-periodikum-select.scss, src/stories/material-header/material-periodikum-select.tsx
This PR introduces a Material App "page" story, that contains Material Header.
The purpose of this is to create css classes that place all components in order and with correct spacing to each other.
**Mobil**
**Desktop**
**With period select**
=> Material App + Material Header

.github/workflows/deployment.yml
Since the change to yarn, something started to go wrong when deploying
to the same version twice. This maybe fixes it?
=> Reverting some of the deployment action cmds

base.scss, src/stories/Library/search-result-page/SearchResultInfo.tsx, src/stories/Library/search-result-page/SearchResultPage.stories.tsx, src/stories/Library/search-result-page/SearchResultPage.tsx, src/stories/Library/search-result-page/SearchResultPager.tsx, src/stories/Library/search-result-page/SearchResultTitle.tsx, src/stories/Library/search-result-page/SearchResultZero.tsx, src/stories/Library/search-result-page/search-result-info.scss, src/stories/Library/search-result-page/search-result-page.scss, src/stories/Library/search-result-page/search-result-pager.scss, src/stories/Library/search-result-page/search-result-title.scss, src/stories/Library/search-result-page/search-result-zero.scss
This PR adds a collection of components used for search results page.
The components are shows as a page in a storybook component called search-result-page.
The primary task of the page component is to position each atom/component correctly in relation to one another.
You can see the search result page here:
Design in Figma: https://www.figma.com/file/ETOZIfmgGS1HUfio57SOh7/S%C3%B8gning?node-id=4557%3A15899
Component in Storybook: search-result-page
The component has props to change the title, link and total result number. This allows users to see how text will wrap when text length increases. It is also possible to toggle zero result to see the page if it does not succeed in finding results.
=> Add Search Result Page and its sub components.

src/stories/Library/Forms/checkbox/Checkbox.stories.tsx, src/stories/Library/Forms/checkbox/Checkbox.tsx, src/stories/Library/Forms/checkbox/checkbox.scss, src/stories/Library/Lists/list-empty/ListEmpty.stories.tsx, src/stories/Library/Lists/list-materials/ListMaterials.tsx, src/stories/Library/Modals/modal-loan/ModalLoan.tsx
Its is to be used in the lists in the modal with checkboxes. So the label is supposed to say something like "select material", and only be 'visible' for screen readers.
=> 5389: add hide label modifier to checkbox

base.scss, src/stories/Library/horizontal-term-line/HorizontalTermLine.tsx, src/stories/Library/horizontal-term-line/horizontal-term-line.scss, src/stories/Library/material-description/MaterialDescription.tsx, src/stories/Library/material-description/material-description.scss, src/stories/Library/search-result-item/SearchResultItem.stories.tsx, src/stories/Library/search-result-item/SearchResultItem.tsx
This PR does two things
- Change the name of SeriesLine to HorizontalTermLine
The name has been changed because it is a reusable component and before it was prefix with: material-
- Change css width for material-description
Only material-description__content should have a max width
=> Rewrite SeriesLine to HorizontalTermLine

src/stories/Library/links/links.scss
Fix so links wont obtain the full width of its container, but instead stay the width of its content.
Before:
After:
=> Fix link width

src/stories/Blocks/header/header.scss, src/stories/Blocks/status-userprofile/statusUserprofile.stories.tsx, src/stories/Blocks/status-userprofile/statusUserprofile.tsx, src/stories/Library/autosuggest-text/autosuggest-text.scss
Despite the grid layout of the header which ensures that first and
second level are always full height we need to ensure that this is
the case for the second level. We mount our search app into the menu
and thus the mount point is injected between .header__menu and 
.header__menu-second.
The mount point will then get the full height but it will be missing
for .header__menu-second.
Explicitly set full height to ensure that the search bar takes up
the entire element and the search string is neatly center aligned
vertically.
Before:
After:
=> Ensure second menu level is always full height

src/stories/Library/Forms/checkbox/Checkbox.stories.tsx, src/stories/Library/Forms/checkbox/Checkbox.tsx, src/stories/Library/Forms/checkbox/checkbox.scss
https://platform.dandigbib.org/issues/5391
This pr adds the posibility of showing a link at the end of a checkboxs text label. For instance to use when accepting terms or similar.
=> 5391: Add label text link

src/stories/Library/disclosure/Disclosure.tsx, src/stories/Library/disclosure/disclosure.scss, src/styles/scss/shared.scss
We have many icons used throughout the project. They are normally black,
but sometimes we need them to be white. We prefer not to set SVG's
directly into the code if we use them many places, but rather refer to
the original svg files as background sources for image tags. (If in the
future we want to change icon x to icon y we only have to exchange the
source file instead of hunting every instance in the code.) 
Thus we need this class.
The chromatic test is not ✅-ed because the visual changes to the app were
not caused by this PR. ([Chromatic + cross-fork PRs i designsystemet](https://dpl.zulipchat.com/#narrow/stream/323076-CMS-NEXT/topic/Chromatic.20.2B.20cross-fork.20PRs.20i.20designsystemet))
The plan is to merge this PR in without approving these changes in Chromatic.
=> Introduce and use a new shared class for inverting icons

.github/workflows/chromatic.yml
This way we should be able to use Chromatic across forks without
forcing contributors to add the project token as a secret. This 
should allow us to merge contributions with increased confidence.
Exposing tokens like this may not seem like a good idea but it is an
approach suggested by Chromatic:
https://www.chromatic.com/docs/custom-ci-provider#run-chromatic-on-external-forks-of-open-source-projects
Sharing project-token‘s allows contributors and others to run 
Chromatic. They’ll be able to use our snapshots. They will not be 
able to get access to our account, settings, or accept baselines. 
This is an acceptable tradeoff for us.
=> Add shared Chromatic project token to GitHub Actions

base.scss, src/stories/Blocks/material-manifestation-item/MaterialMainfestationItem.tsx, src/stories/Library/Lists/list-find-on-shelf/ListFindOnShelf.stories.tsx, src/stories/Library/Lists/list-find-on-shelf/ListFindOnShelf.tsx, src/stories/Library/Lists/list-find-on-shelf/list-find-on-shelf.scss, src/stories/Library/Modals/modal-find-on-shelf/ModalFindOnShelf.stories.tsx, src/stories/Library/Modals/modal-find-on-shelf/ModalFindOnShelf.tsx, src/stories/Library/Modals/modal-find-on-shelf/modal-find-on-shelf.scss, src/stories/Library/availability-label/AvailabilityLabel.stories.tsx, src/stories/Library/availability-label/AvailabilityLabel.tsx, src/stories/Library/disclosure/Disclosure.stories.tsx, src/stories/Library/disclosure/Disclosure.tsx, src/stories/Library/disclosure/disclosure.scss, src/stories/Library/material-header/MaterialHeader.tsx, src/stories/Library/search-result-item/SearchResultItem.tsx, src/stories/availability-label/types.tsx, src/styles/scss/shared.scss
https://reload.atlassian.net/browse/DDFSOEG-227
This PR adds the find on shelf modal and as a part of it:
- new disclosure variant - with availability label
- new availability label variant - without manifestation type
- Find on shelf list component, its story and styling
- Find on shelf modal component, its story and styling
Disclosure with availability label:
Availability label without manifestation type:
Find on shelf list:
Find on shelf modal:
I disabled the controls for Availability label because all the different controls are covered in the specific stories and it can get  pretty confusing switching between the stories and seeing cached availability labels that don't correspond to the story.
=> Find on shelf modal

src/stories/Blocks/material-page/material-page.scss
This PR fixes spacing on the material page based on feedback from DDF by adding bottom padding. (marked purple on the picture below)
Mobile:
=> Fix / Add bottom padding to material page

.markdownlint-cli2.yaml
The current approach to disabling the linting rule does not work.
We allow duplications except for siblings as this does not make sense structurally.
=> Fix markdownlint

src/stories/Library/Modals/modal-profile/modal-profile.scss
This must be a mistake that was not detected when we added padding to all modals
Please check chromatic 
https://www.chromatic.com/test?appId=616ffdab9acbf5003ad5fd2b&id=633c13831c3e24f30298fa25
=> Remove default padding from profile modal

src/stories/Library/Modals/Modal.tsx, src/stories/Library/Modals/modal-cta/ModalCTA.tsx, src/stories/Library/Modals/modal-details/ModalDetails.tsx, src/stories/Library/Modals/modal-find-on-shelf/ModalFindOnShelf.tsx, src/stories/Library/Modals/modal-loan/ModalLoan.tsx, src/stories/Library/Modals/modal-login/ModalLogin.tsx, src/stories/Library/Modals/modal-pause/ModalPause.tsx, src/stories/Library/Modals/modal-profile/ModalProfile.tsx, src/stories/Library/Modals/modal-search/ModalSearch.tsx, src/stories/Library/Modals/modal-text/ModalText.tsx, src/stories/Library/Modals/modal.scss
All the logic for toggle css class .modal-show is now collected in the component. it means that changes only have to take place in one place and that the various components become more readable
Since it is not an element but a block by itself, it must have its own css class
**I have checked in [dpl-react] and it is not used there yet, so this should not cause problems**
=> Move logic to show modal into the Modal component

src/stories/Library/campaign/campaign.scss
If the image is small, we need to use min-width together with breakpoint max-width to overwrite regular campaign's image breakpoint (where the max-width is set to 30%).
=> Use min-width: 100% for an "image only" campaign to handle small images

src/stories/Library/list-buttons/ListButtons.tsx, src/stories/Library/list-buttons/list-buttons.scss
Link til låneliste ? -> https://platform.dandigbib.org/issues/5387
Hidden explanation for screen readers
:)
=> CMN-293: add  screen-reader-description

src/stories/Library/Lists/list-reservation/list-reservation.scss
https://platform.dandigbib.org/issues/5548
Margin zero on desktop, so the author and serie title does not have space between them
=> 5548: margin zero on deskop

src/stories/Library/search-result-item/search-result-item.scss
https://reload.atlassian.net/browse/DDFSOEG-356
Sets min height on search result items In order to reduce cumulative layout shift.
=> Set min height on search result items

src/stories/Library/search-result-item/SearchResultItem.tsx, src/stories/Library/search-result-item/search-result-item.scss
Previously, the titles were always displayed with an underline (if there is an a tag around the title). By implementing hover-based underlining, the underlines will only be displayed when the user hovers their cursor over the title. This improves the visual appeal and user experience of the search results page.
The first element is shown with a hover
* The underline could not be seen in the design system, but it could be seen in dpl-react, because we have used a link tag around the title.
=> Implementing hover-based underlining for searchResultItem title

src/stories/Library/search-result-page/ResultPager.tsx, src/stories/Library/search-result-page/SearchResultPage.stories.tsx, src/stories/Library/search-result-page/SearchResultPage.tsx, src/stories/Library/search-result-page/SearchResultTitle.stories.tsx, src/stories/Library/search-result-page/SearchResultTitle.tsx, src/styles/scss/shared.scss
https://reload.atlassian.net/browse/DDFSOEG-371
To be used for show loading state in a text.
Adds animated ellipsis to the end of a text.
Used by the search header title in the first place.
=> Adding text-loading class

src/stories/Library/search-result-item/SearchResultItem.stories.tsx, src/stories/Library/search-result-item/SearchResultItem.tsx, src/stories/Library/search-result-item/search-result-item.scss, src/stories/Library/search-result-page/SearchResultPageData.ts
https://reload.atlassian.net/browse/DSC-8
The search result cards had fixed height, which didn't account for content overload. This resulted in the excess content to bleed out of the cards - in some cases even overlaying other elements on the page. 
Now we make sure that on desktop long titles get cut off after two lines, and suffixed with three dots. If there are too many availability labels present, the whole card expands in height. 
Mobile implementation stays the same - cards expand and titles are always shown in their full length. 
mobile: 
desktop:
n/a
=> Unify the search result cards

architecture/adr-001-skeleton-screens.md, base.scss, package.json, src/stories/Library/search-result-item/SearchResultItem.stories.tsx, src/stories/Library/search-result-item/SearchResultItemSkeleton.tsx, src/stories/Library/search-result-item/search-result-item-skeleton.scss, src/styles/scss/skeleton.scss, yarn.lock
https://reload.atlassian.net/browse/DDFSOEG-374
Add skeleton screen css for loading state style and implement it on a search result
=> Add skeleton screen css for loading state style

src/stories/Blocks/material-banner/MaterialBanner.stories.tsx, src/stories/Library/Modals/modal-details/ModalDetails.tsx, src/stories/Library/colors/color-classes.scss, src/stories/Library/colors/color-variables.scss, src/stories/Library/colors/identity-color/IdentityColor.tsx, src/stories/Library/cover/Cover.stories.tsx, src/stories/Library/cover/Cover.tsx
https://reload.atlassian.net/browse/DDFSOEG-389
**Figma:**
https://www.figma.com/file/ETOZIfmgGS1HUfio57SOh7/S%C3%B8gning?node-id=4517%3A17645&t=prvkjmQxLeKEuX9U-4
=> Refactor Cover identity tint

src/stories/Library/Lists/list-reservation/list-reservation.scss
https://platform.dandigbib.org/issues/5606
The filter disturbs the stacked effect on hover, so its removed for stacked items
=> 5606: filter none on hover on stacked items

src/stories/Library/Modals/modal-infomedia/Infomedia.tsx, src/stories/Library/Modals/modal-infomedia/infomedia.scss, src/stories/Library/search-result-item/SearchResultItem.tsx, src/stories/Library/search-result-page/search-result-page.scss, src/styles/scss/reset.scss
https://reload.atlassian.net/browse/DDFSOEG-408
https://reload.atlassian.net/browse/DDFSOEG-409 
it is not desired because we want to use the article for semantic reasons, not for styling. 
**The only place in the design system where this has a consequence is in Infomedia**
Therefore, I have added a new CSS class to keep the desired styling of infomedia articles
**This PR also fix padding for the search result page**
This was discovered because we have used article element for semantic reasons in search-result-item in dpl-react
=> Remove default spacing in article + Add spacing in infomedia + Change padding for the search result page

src/stories/Blocks/material-banner/material-banner.scss, src/stories/Library/Modals/Modal.tsx, src/stories/Library/Modals/ModalShared.tsx, src/stories/Library/Modals/modal-facet-browser/FacetBrowser.tsx, src/stories/Library/Modals/modal-loan/modal-loan.scss, src/stories/Library/Modals/modal-login/ModalLogin.tsx, src/stories/Library/Modals/modal-profile/ModalProfile.tsx, src/stories/Library/Modals/modal-text/modal-text.scss, src/stories/Library/Modals/modal.scss, src/styles/scss/shared.scss
https://reload.atlassian.net/browse/DSC-27
This PR adjusts the modal styling component to by default not fill the entire screen. This change affected other stories and uses of the modal component and its content. The biggest change that I introduced is to Material Banner - because the modal is smaller, the chromatic snapshot showed it looking quite broken. I adjusted the number of items that fit in a single row for tablets/smaller screen laptops (from 4 to 3).
n/a
=> Make all full-screen modals smaller as default styling

src/stories/Library/review/review.scss, src/stories/Library/typography/Typography.tsx, src/stories/Library/typography/typography.scss
https://reload.atlassian.net/browse/DDFSOEG-417
This PR introduces a new typography class - text small caption bold. This is then used for review headlines.
n/a
=> Add bold caption styling

base.scss, src/stories/Blocks/material-page/MaterialPage.stories.tsx, src/stories/Blocks/material-page/MaterialPageSkeleton.tsx, src/stories/Blocks/material-page/material-page-skeleton.scss, src/stories/Library/recommender/Recommender.tsx, src/stories/Library/search-result-item/SearchResultItemSkeleton.tsx, src/stories/Library/search-result-item/search-result-item-skeleton.scss, src/stories/Library/search-result-page/SearchResultPage.stories.tsx, src/stories/Library/search-result-page/SearchResultPageSkeleton.tsx, src/stories/Library/search-result-page/search-result-page-skeleton.scss
https://reload.atlassian.net/browse/DDFSOEG-400
Adds skeleton screens to the material page.
And as a bonus improves the lengths of the skeleton lines on search results.
=> Material page skeleton screens (Performance optimisations)

src/stories/Library/disclosure/disclosure.scss, src/stories/Library/horizontal-term-line/HorizontalTermLine.tsx, src/stories/Library/horizontal-term-line/horizontal-term-line.scss, src/stories/Library/recommender/recommender.scss, src/styles/scss/reset.scss
https://reload.atlassian.net/browse/DSC-37
- Limits the number of terms displayed to the value set in numberOfItemsToShow, which is set to 2.
- a toggle button has been added, allowing users to switch between displaying only the limited number of terms and all of them. The button features a toggle icon that changes according to the component's state.
**Other Changes**
- A new CSS class for the icon and a modifier to flip the arrow direction have been introduced in horizontal-term-line.
- The modifier used in DisclosureControllable has been renamed and a transition has been added.
- CSS for the default Disclosure component that uses 'details' has been added
=> Improved expand icon animation in 'horizontal-term-line' and 'disclosure'

src/stories/Library/material-header/material-header.scss
https://reload.atlassian.net/browse/DDFSOEG-418
This change will keep the cover in place and ensure that the center of the container remains unchanged."
=> Add min-height to 'material-header'

src/stories/Library/availability-label/AvailabilityLabel.tsx, src/stories/Library/availability-label/availability-label.scss
https://reload.atlassian.net/browse/DDFSOEG-430
This PR makes sure text inside availability labels can't have a bottom margin.
We need to make sure that accessibility tools don't add a it to this text, as it would then be unreadable - hidden. We can afford to do this as there is no paragraph of text following the text inside availability labels.
n/a
Connected PR taking these changes to dpl-react repository: https://github.com/danskernesdigitalebibliotek/dpl-react/pull/372
=> Fix availability label accessibility

base.scss, src/stories/Library/scroll-lock-background/scroll-lock-background.scss
https://platform.dandigbib.org/issues/5533
PR which uses this class:
https://github.com/danskernesdigitalebibliotek/dpl-react/pull/311
A class for toggling a scroll-lock. Applied to elements behind an open modal to prevent scrolling.
N/A
=> adding class to prevent background from scrolling

src/stories/Blocks/material-manifestation-item/MaterialMainfestationItem.tsx, src/stories/Blocks/material-page/MaterialPage.tsx, src/stories/Library/Modals/modal-facet-browser/FacetBrowser.tsx, src/stories/Library/Modals/modal-find-on-shelf/ModalFindOnShelf.tsx, src/stories/Library/disclosure/Disclosure.stories.tsx, src/stories/Library/disclosure/Disclosure.tsx, src/stories/Library/heading/Heading.stories.tsx, src/stories/Library/heading/Heading.tsx, src/stories/Library/horizontal-term-line/HorizontalTermLine.tsx, src/stories/Library/review/Review.tsx
https://reload.atlassian.net/browse/DDFSOEG-452
https://reload.atlassian.net/browse/DDFSOEG-422
https://reload.atlassian.net/browse/DDFSOEG-423
To improve user navigation and content comprehension
The component allows for dynamic generation of the HTML tag based on the level prop provided, which can be one of four options (h2, h3, h4, or h5).
=> Refactor headings tree structure for `Material Page`

base.scss, src/stories/Library/Buttons/button/button-expand/ButtonExpand.tsx, src/stories/Library/Buttons/button/button-expand/button-expand.scss, src/stories/Library/Buttons/button/button-expand/button-expand.stories.tsx, src/stories/Library/horizontal-term-line/HorizontalTermLine.tsx, src/stories/Library/horizontal-term-line/horizontal-term-line.scss
https://reload.atlassian.net/browse/DDFSOEG-488
This pull request addresses alignment issues in the horizontal-term-line component and improves reusability by extracting the ButtonExpand functionality into a separate component.
See https://www.chromatic.com/test?appId=616ffdab9acbf5003ad5fd2b&id=643e7cc368aa7db42330a82e
Here are the reflecting changes in dpl-react
https://github.com/danskernesdigitalebibliotek/dpl-react/pull/421
=> Ensure baseline alignment for `HorizontalTermLine` + Separate `ButtonExpand` component

src/stories/Library/card-list-item/card-list-item.scss
https://reload.atlassian.net/browse/DDFSOEG-514
This pull request addresses the issue where letters like 'g' are cut off at the bottom.
To fix this, I added a `min-height` property to the `.search-result-item__title` class. This prevents letters like "g" from getting cut off due to the use of `text-overflow: ellipsis;` and `overflow: hidden;`. With the inclusion of `min-height: 30px;`, the display is now correct.
Screenshot is from dpl-react
Remember to update the dpl-design-system in dpl-react
=> Fix 'g' letters being cut at the bottom.

src/stories/Blocks/material-page/MaterialPageSkeleton.tsx, src/stories/Blocks/material-page/material-page-skeleton.scss
https://reload.atlassian.net/browse/DDFSOEG-522
This PR is changing the `MaterialPageSkeleton` to reflect the new cover size on mobile.
https://www.chromatic.com/build?appId=616ffdab9acbf5003ad5fd2b&number=866
https://github.com/danskernesdigitalebibliotek/dpl-react/pull/438
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/312
=> Update `MaterialPageSkeleton` to reflect the new cover size on mobile

src/stories/Library/Lists/list-materials/ListMaterials.stories.tsx, src/stories/Library/Lists/list-materials/ListMaterials.tsx, src/stories/Library/Lists/list-materials/list-materials.scss, src/stories/Library/Modals/modal-loan/ModalLoan.stories.tsx, src/stories/Library/Modals/modal-loan/ModalLoan.tsx
https://platform.dandigbib.org/issues/5593
Update mobile view of group modal 
[If your change affects the user interface you should include a screenshot of the result with the pull request.](https://616ffdab9acbf5003ad5fd2b-pkdpqfcuza.chromatic.com/?path=%2Fstory%2Flibrary-lists-materials--item)
https://616ffdab9acbf5003ad5fd2b-pkdpqfcuza.chromatic.com/?path=%2Fstory%2Flibrary-modals-loan--modal-loan-expired
https://616ffdab9acbf5003ad5fd2b-pkdpqfcuza.chromatic.com/?path=%2Fstory%2Flibrary-modals-loan--modal-loan-expires-soon
https://616ffdab9acbf5003ad5fd2b-pkdpqfcuza.chromatic.com/?path=%2Fstory%2Flibrary-modals-loan--modal-loan-sticky-button-in-bottom
n/a
=> ITKDEV - 5593 - Mobile view of group modal

src/stories/Library/card-list-item/card-list-item.scss
https://reload.atlassian.net/browse/DDFSOEG-514
This pull request addresses an issue where the lower part of letters was being cut off in `CardListItem` titles due to the usage of the `ellipsis` property. 
To resolve this, the following changes have been implemented:
- Added a line-height of 30 px to ensure there is enough space for the text.
=> Fix lower part of letters being cut off in `CardListItem` titles

src/stories/Library/Forms/input/input.scss
https://platform.dandigbib.org/issues/5820
Removed "confusing arrows"
n/a
=> 5820: remove arrows from number input

.github/workflows/deployment.yml
Dependabot does not have permissions to create deployments. This causes  the workflow to fail.
According to GitHub having Dependabot run with read-only scopes is  intentional and the recommended approach is to skip running such  workflows based on branch naming:
https://docs.github.com/en/code-security/code-scanning/troubleshooting-code-scanning/resource-not-accessible-by-integration
This is a sister PR to danskernesdigitalebibliotek/dpl-react#546
=> Skip deploy workflow for Dependabot

src/stories/Library/Lists/list-dashboard/list-dashboard.scss, src/stories/Library/status-label/status-label.scss
https://reload.atlassian.net/browse/DDFLSBP-207
The current implementation does not hide the dashboard arrow on mobile devices which gives limited space for the status label.
I allowed more space by hiding the arrow on mobile and added less line hight for the status label.
Normal size mobile
Small size mobile
=> Improved space for status label in list dashboard

.github/dependabot.yml
We use many packages from Storybook. These are often updated in parallel  and may have dependencies between them. Thus is makes sense to group  updates of these packages in Dependabot to ensure that we get an update  to e.g. Storybook 7 in the same pull request.
=> Group Dependabot updates for Storybook

src/stories/Library/Lists/list-dashboard/list-dashboard.scss
This is a follow-up on below issue
https://reload.atlassian.net/browse/DDFLSBP-207
The current implementation does not align the status labels and gives a bit messy dashboard. On mobile we want to align the labels to the right.
=> Align label right on mobile

base.scss, src/stories/Library/Modals/modal-loan/ModalLoan.tsx, src/stories/Library/Modals/modal-loan/modal-loan.scss, src/stories/Library/button-box/ButtonBox.stories.tsx, src/stories/Library/button-box/StickyButtonBoxMobileOnly.tsx, src/stories/Library/button-box/button-box.scss, src/stories/Library/loan-list-page/loan-list-page.scss, src/styles/scss/shared.scss
https://reload.atlassian.net/browse/DDFLSBP-57
This PR  introduces the button box and sticky button box concept.
The footer box classes were created in order to accomodate the sticky renewal button on the loan page when watching it on a mobile device.
The button box classes replaces the modal-loan__buttons classes, since button box is more generic and used not only in modals.
https://github.com/danskernesdigitalebibliotek/dpl-design-system/assets/998889/6f1d37a3-3635-4929-9f3c-6629d8cf641f
=> Introducing button box

src/stories/Library/Buttons/button/buttons.scss
https://reload.atlassian.net/browse/DDFLSBP-77
Buttons have a very "dead" interaction, and we need to show the user when they hover it. This adds some opacity to filled hovered buttons, and fill to outlined hovered buttons. It also aligns the filled disabled state with the figma design
=> Added hover state for buttons

src/stories/Library/pause-reservation/PauseReservation.stories.tsx, src/stories/Library/pause-reservation/PauseReservation.tsx, src/stories/Library/pause-reservation/pause-reservation.scss
https://reload.atlassian.net/browse/DDFLSBP-70
The pause reservation banner has been improved and storybook will now reflect that.
The previous styling did not handle small screens very well. This both takes care for smaller devices and cleans up some CSS.
Before:
After:
=> Refactor pause reservation banner

src/stories/Library/Lists/list-materials/list-materials.scss, src/stories/Library/Lists/list-reservation/list-reservation.scss, src/stories/Library/status-label/status-label.scss
https://reload.atlassian.net/browse/DDFLSBP-278
https://reload.atlassian.net/browse/DDFLSBP-279
They were just put in roughly everywhere needed in dpl-react so the different views in group-modal and reservation-list had to be adjusted.
=> Improve rendering of reservation labels

src/stories/Blocks/article/Article.stories.tsx, src/stories/Blocks/article/Article.tsx, src/stories/Library/article-header/ArticleHeader.tsx, src/stories/Library/article-header/article-header.scss, src/stories/Library/links/links.scss, src/stories/Library/typography/typography.scss
https://reload.atlassian.net/browse/DDFFORM-9
This pull request introduces a refactor of the CSS for the `article-header`, aligning with our team's recent strategic shift in styling practices. We are transitioning from the use of utility classes to an extend inside BEM classes.
Additionally, the markup has been revised to improve semantic structure.
=> Refactor `article-header` CSS Following Strategy Shift

src/stories/Blocks/event-page/EventPage.stories.tsx, src/stories/Library/Lists/list-description/ListDescription.tsx, src/stories/Library/Lists/list-description/ListDescriptionFakeData.tsx, src/stories/Library/Lists/list-description/list-description.scss
https://reload.atlassian.net/browse/DDFFORM-57
This PR adds support for displaying prices for events. Prices are shown next to descriptions.
An important part of the handling is the support of multiple categories and prices. Instead of adding each category as a separate entry they now get a single price entry containing each of the categories. This makes sense - especially when you look at the mobile view.
To prevent categories from wrapping a new modifier is added to the `list-description` block.
=> Event prices

src/stories/Blocks/event-page/EventPage.stories.tsx, src/stories/Library/image-credited/ImageCredited.stories.tsx, src/stories/Library/image-credited/ImageCredited.tsx, src/stories/Library/image-credited/image-credited.scss, src/styles/scss/tools/placeholder.scss
https://reload.atlassian.net/browse/DDFFORM-93
This pull request introduces the "identity" CSS class to manage scenarios involving missing images. 
- Implementation of the `%identity-placeholder` class, which sets the background color and adds a bold border.
- Introduction of the `image-credited__no-image class`, an extension of `%identity-placeholder`.
- Addition of the `height: auto` property to img elements, ensuring the aspect ratio of images is maintained.
=> Adding 'Identity' CSS for missing `event` image

src/stories/Library/event-description/event-description.scss, src/stories/Library/event-header/event-header.scss, src/stories/Library/link-with-icon/link-with-icon.scss, src/stories/Library/medias/medias.scss, src/stories/Library/rich-text/rich-text.scss, src/styles/scss/tools.scss, src/styles/scss/tools/mixins.misc.scss, src/styles/scss/tools/variables.layout.scss
[Make sure that rich-text has spacing and margin. DDFFORM-5](https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/390/commits/dd485fb3e1a484e554a62a8195b8f4affa8e5f40) 
It worked in Storybook, but not in Drupal.
That is because Storybook adds its own wrapper, which made it appear
correct.
----
Add a layout-container mixin, and replace any existing max-widths.
=> Fix rich text + Re-factor layout max width as a mixin

base.scss, package.json, src/stories/Library/Forms/date-picker/DatePicker.stories.tsx, src/stories/Library/Forms/date-picker/DatePicker.tsx, src/stories/Library/Forms/date-picker/date-picker.scss, src/stories/Library/Forms/date-picker/datepicker.scss, src/stories/Library/date-calendar/DateCalendar.tsx, src/stories/Library/date-calendar/DatePicker.stories.tsx, src/stories/Library/date-calendar/date-calendar.scss, yarn.lock
https://reload.atlassian.net/browse/DDFLSBP-351
We needed to find a find to share a datepicker across React and Drupal with the same styling applied both places.
This PR introduces flatpickr JS as the foundation for our new datepicker. The design system makes sure that flatpickr is styled the same way whereever it is used, and it is up to the respective app to implement flatpickr how it sees fit. The React app could for example use the Flatpickr React package and Drupal the native JS package. It does really not matte, because the flatpickr is the same. 
The bare bone date calendar
The date calendar implemented as a datepicker
=> Added flatpickr

src/stories/Library/Modals/modal-cta/ModalCTA.tsx, src/stories/Library/Modals/modal-cta/modal-cta.scss
- Updated mobile responsiveness for modalCTA item component.
I found this as a part of going through UI tests as part of changing the fonts. 
Found a component that was not responsive. Made it responsive. 
See the UI test that must be accepted in order to see the change.
=> fix old non responsive stories

src/stories/Blocks/footer/footer.scss, src/stories/Library/Lists/list-dashboard/list-dashboard.scss
https://reload.atlassian.net/browse/DDFLSBP-183
This fixes an issue where the footer will take up too much space on the x-axis and overflow the main content. When using window sizing like vw or vh, scrollbars are counted in, and this will add additional unneeded space.
=> Fix overflow on x-axis

src/stories/Library/Modals/modal-loan/modal-loan.scss
overflow: scroll, will always show a scrollbar, which is very ugly
=> Only show scrollbar when content is overflowing

base.scss, src/stories/Blocks/event-page/EventPage.tsx, src/stories/Library/event-description/event-description.scss, src/stories/Library/event-header/event-header.scss, src/stories/Library/event-paragraphs/EventParagraphs.tsx, src/stories/Library/event-paragraphs/event-paragraphs.scss, src/stories/Library/rich-text/RichText.tsx
https://reload.atlassian.net/browse/DDFFORM-94
This Pull Request introduces the EventParagraphs component and incorporates the layout container mixin where necessary.
=> Add `EventParagraphs` component to EventPage + Use layout-container where its needed

src/stories/Library/Buttons/button/buttons.scss
https://reload.atlassian.net/browse/DDFLSBP-55
To comply with the laws of WCAG, we need a distinctive style for focused buttons.
This needs to be an outline with at least 2px wideness, and a clear difference in contrast
=> Added explicit focus  styles for buttons

src/stories/Library/Modals/modal-loan/modal-loan.scss
https://reload.atlassian.net/browse/DDFLSBP-295
The scrollbar should appear on the side of the modal, not on elements inside the modal.
n/a
=> Don't set overflow-y auto on modal-loan__container

src/stories/Library/Buttons/icon-button/icon-button.scss, src/stories/Library/accordion/accordion.scss, src/stories/Library/dropdown/dropdown.scss, src/styles/scss/tools/placeholder.scss
https://reload.atlassian.net/browse/DDFLSBP-216
To comply with the laws of WCAG, we need a distinctive style for focused dropdown/select boxes.
This needs to be an outline with at least 2px wideness, and a clear difference in contrast
Dropdown default
Dropdown focused
Accordion default
Accordion focused
=> Focus outline on dropdowns

src/stories/Blocks/header/header.scss
This commit adds the `text-decoration: none` property to the `header__logo-desktop-link` class in the `header.scss` file. 
This ensures clean fallback text for the logo within the anchor tag.
=> Implement `text-decoration: none` on `header__logo-desktop-link`

.stylelintrc, base.scss, package.json, src/stories/Library/Arrows/arrows.scss, src/stories/Library/Lists/list-materials/list-materials.scss, src/stories/Library/Lists/list-reservation/list-reservation.scss, src/stories/Library/card/Card.stories.tsx, src/stories/Library/card/Card.tsx, src/stories/Library/card/card.scss, src/stories/Library/shadows/shadows.scss, src/stories/Library/slider/Slider.stories.tsx, src/stories/Library/slider/Slider.tsx, src/stories/Library/slider/init-slider.js, src/stories/Library/slider/slider.scss, src/styles/scss/legacy/pagefold.legacy.scss, src/styles/scss/legacy/spacings.legacy.scss, src/styles/scss/tools/mixins.misc.scss, src/styles/scss/tools/mixins.tools.scss, src/styles/scss/tools/placeholder.scss, src/styles/scss/tools/variables.breakpoints.scss, src/styles/scss/tools/variables.colors.scss, src/styles/scss/tools/variables.spacings.scss, src/styles/scss/tools/variables.typography.scss, yarn.lock
Remove bem-namics rule from stylelint.
It appears that it does not work as intended:
It reports errors where it shouldnt, and doesnt
report errors where it should.
Ontop of that, it seems to cause a bug with // stylelint-disable-line.
A lot of the files we choose to ignore it anyway,
so we might aswell just remove it.
----
Card slider, and placeholder/pagefold refactor. DDFFORM-86
- Introduce a 'card' story, which corresponds to the 'news card'
in Figma.
- Cards can support images, or just a teaser text, shown in the
page fold, placeholder style.
- I've simplified the placeholder/pagefold functionality,
using %placeholders and making them responsive, instead of
defining specific sized HTML elements.
- I've also included the 'SwiperJS' library, for the slider.
- SwiperJS was chosen, as the …
=> Card slider, and placeholder/pagefold refactor. DDFFORM-86

src/styles/scss/reset.scss
Set the page background on the whole body, to avoid margin issues.
Up until now, we've added the page background on various
individual components, but this is a problem if there is
margin between elements, when we want the BG to continue.
=> Fix styling

base.scss, src/stories/Library/event-header/EventHeader.tsx, src/stories/Library/event-header/event-header.scss, src/stories/utils/show-more.js, src/stories/utils/show-more.md, src/stories/utils/show-more.scss
https://reload.atlassian.net/browse/DDFFORM-130
This pull request introduces the `show more` feature as a utility for use in Drupal / dpl-cms, specifically designed for `HorizontalTermLine` and `Tags`. 
It also includes a refactor of the `EventHeader` component, enabling it to manage multiple tags if needed.
=> Implement `show more` functionality as a utility

base.scss, src/stories/Library/link-with-icon/link-with-icon.scss, src/stories/Library/paragraph/paragraph.scss, src/stories/Library/paragraphs/Paragraphs.tsx, src/stories/Library/paragraphs/paragraphs.scss
Fix spacing between links/files paragraph items + Better class name.
- Make sure 'files' paragraph works in same way as 'links'
- Use `.paragraphs__item` instead of `.paragraph`, to avoid that
we style on a class name that Drupal might use in situations
we are not interested in.
=> Paragraph tweaks

src/stories/Library/Arrows/arrows.scss, src/stories/Library/Lists/list-materials/list-materials.scss, src/stories/Library/Modals/modal-details/modal-details.scss
https://reload.atlassian.net/browse/DDFLSBP-142
The scrollbar is now only on the very right side of the modal and there isn't any blank space on the bottom of the modal where content is cut off.
-
=> Remove content inner scrollbar from modals

src/stories/Blocks/article/Article.stories.tsx, src/stories/Blocks/article/Article.tsx, src/stories/Library/Modals/modal-facet-browser/FacetBrowser.tsx, src/stories/Library/article-header/ArticleHeader.tsx, src/stories/Library/card-list-page/FacetLine.tsx, src/stories/Library/card-list-page/FacetLineSelectedTerms.tsx, src/stories/Library/event-description/EventDescription.tsx, src/stories/Library/event-header/EventHeader.tsx, src/stories/Library/event-list-item/EventListItem.tsx, src/stories/Library/horizontal-term-line/HorizontalTermLine.tsx, src/stories/Library/tag/Tag.stories.tsx, src/stories/Library/tag/Tag.tsx, src/stories/Library/tag/tag-button/TagButton.stories.tsx, src/stories/Library/tag/tag-button/TagButton.tsx, src/stories/Library/tag/tag-link/TagLink.stories.tsx, src/stories/Library/tag/tag-link/TagLink.tsx, src/stories/Library/tag/tag.scss
[Please add a link to the issue being addressed by this change.
](https://reload.atlassian.net/browse/DDFFORM-130)
This PR adds support for category and tags for events and articles.
A notable change is the rendering of categories. According to Figma they should use the large tag component on the full view of events and articles.
Check out Chromatic.
=> Taxonomy categories and tags

.github/workflows/create-release-on-branch-changes.yml
In order to try to avoid that a new npm package is not published.
=> Add NODE_AUTH_TOKEN

src/stories/Library/card-grid/CardGrid.stories.tsx, src/stories/Library/card-grid/card-grid.scss, src/stories/Library/card/card.scss, src/stories/Library/slider/slider.scss, src/styles/scss/tools/variables.spacings.scss, src/styles/scss/tools/variables.typography.scss
Adjust card-grid max width, to avoid massive cards. DDFFORM-180
---
Fix cards sizing, and slider 'jumping' DDFFORM-182
- Make every second item in slider have margin-top, to pull it down, instead of based on no-image.
- Add missing mobile styling for tall (medium) cards.
- Add framing to XL card teasers with images
- Adjust the framing and padding on cards, to make them more sensible on smaller screens.
=> Card+Card-grid size tweaks. DDFFORM-180 DDFFORM-182

src/stories/Library/disclosure/Disclosure.stories.tsx, src/stories/Library/disclosure/Disclosure.tsx, src/stories/Library/disclosure/disclosure.scss, src/stories/Library/paragraphs/paragraphs.scss
[jira link](https://reload.atlassian.net/jira/software/c/projects/DDFFORM/boards/485?selectedIssue=DDFFORM-166) 
This PR modifies the current disclosure component with styling needed for using it in the CMS as accordions. 
Have a look at the accepted chromatic changes. Specifically the event page which seems unaltered, yet chromatic is picking up on something.
=> DDFFORM 166 accordion

src/stories/Blocks/event-list-page/event-list-page.scss
- Update heading width for event-list-page
[jira link](https://reload.atlassian.net/jira/software/c/projects/DDFFORM/boards/485?selectedIssue=DDFFORM-235)
This PR aligns the max-width of the heading on the event-page with the updated max-width of the event list items. 
This was supposed to have been a part of a previous PR but was overlooked.
=> adjust event page header

src/styles/scss/tools/variables.typography.scss
42px appears to be some kind of typo - either way, a line-height of 42px when using 16px font-size is extreme and makes no sense. Let's use the 160% that is already being used for `small` instead.
=> Update faulty line-height, to not have broken double-lines.

base.scss, src/stories/Blocks/page/page.scss, src/stories/Library/article-header/ArticleHeader.tsx, src/stories/Library/event-header/EventHeader.tsx, src/stories/Library/event-header/event-header.scss, src/stories/Library/event-list-item/EventListItem.tsx, src/stories/Library/hero/Hero.tsx, src/stories/Library/hero/hero.scss, src/stories/Library/tag/Tag.stories.tsx, src/stories/Library/tag/Tag.tsx, src/stories/Library/tag/tag-list/TagList.stories.tsx, src/stories/Library/tag/tag-list/TagList.tsx, src/stories/Library/tag/tag-list/tag-list.scss
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/733
This PR accomplishes two things: 
- Rename `TagCategories` to `TagList`. 
- Replaces `TagList` with `Tag` in instances where `TagList` is not necessary.
=> Fix tag categories

base.scss, src/stories/Library/nav-spot/NavSpot.stories.tsx, src/stories/Library/nav-spot/NavSpot.tsx, src/stories/Library/nav-spot/nav-spot.scss, src/stories/Library/nav-spots/NavSpots.stories.tsx, src/stories/Library/nav-spots/NavSpots.tsx, src/stories/Library/nav-spots/nav-spots.scss
Introduces a new type of teaser (`nav-spot`), along with a grid-like container (`nav-spots`).
This is more or less the same story, concept etc. as `card-grid`, `nav-grid` and probably others.
Depending on how many items are in `nav-spots`, the individual teasers will be shown in different variants - just like how we do with `card-grid`.
https://reload.atlassian.net/browse/DDFFORM-165
https://www.figma.com/file/Zx9GrkFA3l4ISvyZD2q0Qi/Designsystem?type=design&node-id=1958-7664&mode=design&t=jxpPtsnK91BZqfNm-4
See it in action here:
https://616ffdab9acbf5003ad5fd2b-knpbqbfhfh.chromatic.com/?path=/story/library-nav-spots-navigationsmodul--many
https://616ffdab9acbf5003ad5fd2b-knpbqbfhfh.chromatic.com/?path=/story/library-nav-spots-navigationsmodul--single
=> Nav spots ('Fremhævet navigationskomponent') - DDFFORM-165

base.scss, src/stories/Blocks/event-list-page/EventListPage.tsx, src/stories/Blocks/event-list-page/event-list-page.scss, src/stories/Library/dropdown/dropdown.scss, src/stories/Library/event-list-item/event-list-item.scss, src/stories/Library/input-label/InputLabel.stories.tsx, src/stories/Library/input-label/InputLabel.tsx, src/stories/Library/input-label/input-label.scss
A few minor updates, displaying the dropdown on the event-list-page element.
Also introduces a few small fixes, such as padding on the dropdown.
Easiest to review commit by commit.
See it here:
https://616ffdab9acbf5003ad5fd2b-fakpuatovd.chromatic.com/?path=/story/blocks-event-list-page--default
=> Setup 'categories' exposed filter on event search page. DDFFORM-184

src/stories/Blocks/footer/Footer.stories.tsx, src/stories/Blocks/footer/Footer.tsx, src/stories/Blocks/footer/FooterColumn.tsx, src/stories/Blocks/header/Header.tsx, src/stories/Library/accordion/Accordion.stories.tsx, src/stories/Library/accordion/Accordion.tsx, src/stories/Library/logo/Logo.stories.tsx, src/stories/Library/logo/Logo.tsx
https://reload.atlassian.net/browse/DDFFORM-223
I have refactored the footer stories to align with our standard approach for creating stories. This will result in Chromatic treating them as new stories. As I have another branch where I am performing extensive cleanup and component separation within the footer, it is crucial for this to be merged first. This will allow Chromatic to assist me in the subsequent branch.
=> Refactor `Footer`, `FooterColumn`, `Logo` and `Accordion` stories

src/stories/Blocks/autosuggest/Autosuggest.stories.tsx, src/stories/Blocks/header/Header.tsx, src/stories/Blocks/header/header-state.js, src/stories/Blocks/header/header.scss, src/styles/scss/tools/variables.typography.scss
`.has-burger-menu` is added dynamically using JS, by calculating if there is enough space to show the desktop menu, and otherwise enabling the burger menu.
This required some re-factoring of the header menu system, as I need to measure the width of the desktop menu at all times. So, instead of display: none, we're just hiding it visually.
DDFFORM-220
=> Refactor header, to automatically enable burger-menu when needed.

base.scss, src/stories/Library/Lists/list-dashboard/ListDashboard.stories.tsx, src/stories/Library/Lists/list-dashboard/ListDashboard.tsx, src/stories/Library/Lists/list-dashboard/ListDashboardItemSkeleton.tsx, src/stories/Library/Lists/list-dashboard/list-dashboard-skeleton.scss, src/stories/Library/Modals/GroupModalItemSkeleton.tsx, src/stories/Library/Modals/group-modal-item-skeleton.scss, src/stories/Library/Modals/modal-loan/ModalLoan.stories.tsx, src/stories/Library/Modals/modal-loan/ModalLoan.tsx
https://reload.atlassian.net/browse/DDFLSBP-427
This PR introduces group modal item skeletons with styling and a brand new story.
As a last minute decision, I added dashboard list item skeletons too - to be used on the dashboard and in the user menu.
-
=> Group modal card skeletons

src/stories/Library/slider/init-slider.js
SwiperJS has a hard time understanding how to deal with keyboard focus and setting the slider positioning.
Because we have items with very different widths, and we use "auto" for the actual movement, the focus goes out of sync with the visual visibility. This function is called when the swiper is initialized. We listen on focus within the item wrapper, and when we detect it, we calculate our own transform value, overwriting SwiperJS.
DDFFORM-233
=> Custom movemenet calculator for sliders, when using keyboard tabbing.

src/stories/Library/slider/init-slider.js
We want to make the controls not controllable by keyboard, as it quickly becomes a confusing experience, when the active-slide is not what you get to when you tab along.
This PR comes from @kasperg 's excellent point in https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/504
=> Disable swiper navigation button use with keyboard. DDFFORM-232

src/stories/Library/Modals/modal-details/modal-details.scss, src/stories/Library/Modals/modal-login/modal-login.scss
https://reload.atlassian.net/browse/DDFLSBP-415
This PR adds larger mobile bottom padding to modals on mobile devices in order for the URL bar on iOS not to hide the action button(s) located in the bottom of some modals.
-
=> Add larger mobile bottom padding to modals on mobile devices

src/stories/Library/counter/counter.scss
https://reload.atlassian.net/browse/DDFLSBP-409
We now only capitalize the first letter of the counter label text, as opposed to every word.
-
-
=> Don't capitalize all words in the counter label text, only first letter

src/stories/Library/Modals/modal-infomedia/infomedia.scss, src/stories/Library/Modals/modal-loan/modal-loan.scss, src/stories/Library/Modals/modal.scss
https://reload.atlassian.net/browse/DDFLSBP-454
Fixes various visual bugs:
- modal-loan content of modals wasn't spanning over full width of moals
- modal close button had a background color that was visible when the X was animating outside of modals
-
-
=> Fix various visual bugs

src/stories/Library/slider/init-slider.js
Without this update, it jumped backwards after going into keyboard focus.
=> Use swiper.setTranslate() to avoid double animation. DDFFORM-233

src/stories/Library/content-list-item/content-list-item.scss
https://reload.atlassian.net/browse/DDFFORM-405
This pull request removes the `link-tag` styling from `content-list-item__location` as they are not used as links.
=> Remove link style from `content-list-item__location`

src/styles/scss/tools/variables.typography.scss
- Changing the font-size for `small text caption` because it is too small too meet accessbility for the places it is used.
[Jira link](https://reload.atlassian.net/jira/software/c/projects/DDFFORM/boards/485?assignee=557058%3A9a3dd056-14db-4baf-917f-d89c6c42dceb&selectedIssue=DDFFORM-174)
This superseded #476. Description is copied from that PR. 
This PR changes the base font-size of 'Small text caption" from 10px to 12px. 
The font is used across the system, but it is too small for optimal readability. 
I've left the chromatic changes unaccepted on purpose, so that the review can look through them and see what they think. 
See chromatic tests.
=> DDFFORM 174 update font size small caption

src/stories/Library/availability-label/availability-label.scss
https://reload.atlassian.net/browse/DDFLSBP-475
Setting a specific color for availability-labels texts that would otherwise adopt the default iOS 15 (or later) blue color.
Before:
After:
*
=> Fixing availability-labels texts color on iOS 15 (or later) [DDFLSBP-475]

src/stories/Library/Modals/modal.scss
https://reload.atlassian.net/browse/DDFLSBP-500
Move modal close button 17px to the left so scrollbar isn't obscured - 17 because that is the width of the scrollbar on Windows, which is the thickest one.
-
=> Move modal close button

base.scss, src/stories/Blocks/event-page/EventPage.stories.tsx, src/stories/Blocks/event-page/EventPage.tsx, src/stories/Blocks/page/Page.stories.tsx, src/stories/Blocks/page/Page.tsx, src/stories/Library/Heros/hero-link/HeroLink.stories.tsx, src/stories/Library/Heros/hero-link/HeroLink.tsx, src/stories/Library/Heros/hero/Hero.stories.tsx, src/stories/Library/Heros/hero/Hero.tsx, src/stories/Library/Heros/hero/HeroVisual.tsx, src/stories/Library/Heros/hero/hero.scss, src/stories/Library/card-grid/card-grid.scss, src/stories/Library/card/Card.stories.tsx, src/stories/Library/card/Card.tsx, src/stories/Library/card/card.scss, src/stories/Library/content-list-item/ContentListItem.stories.tsx, src/stories/Library/content-list-item/ContentListItem.tsx, src/stories/Library/content-list-item/content-list-item.scss, src/stories/Library/content-list/ContentList.stories.tsx, src/stories/Library/content-list/ContentListData.tsx, src/stories/Library/image-credited/ImageCredited.tsx, src/stories/Library/image-credited/image-credited.scss, src/stories/Library/media-container/MediaContainer.stories.tsx, src/stories/Library/media-container/MediaContainer.tsx, src/stories/Library/media-container/media-container.scss, src/stories/Library/nav-spot/NavSpot.tsx, src/stories/Library/nav-spot/nav-spot.scss, src/styles/scss/tools/placeholder.scss, src/styles/scss/tools/variables.spacings.scss
Before now, we used various scss mixins to re-use the same placeholder component, that shows up when no image is available. Instead, we'll make a media-container component that can be re-used along with it's own CSS classes.
----
Please review it, by starting to look at the visual changes in chromatic :)
I've also tweaked some of the examples, so we see teasers without images.
-----
**This should not be merged, before we also have the CMS PR ready!**
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/861
=> Refactor media placeholder, making it a seperate component. DDFFORM-360

base.scss, src/stories/Library/opening-hours/OpeningHours.stories.tsx, src/stories/Library/opening-hours/OpeningHours.tsx, src/stories/Library/opening-hours/OpeningHoursDayEntry.tsx, src/stories/Library/opening-hours/OpeningHoursExampleData.ts, src/stories/Library/opening-hours/OpeningHoursWeekList.tsx, src/stories/Library/opening-hours/opening-hours-skeleton.scss, src/stories/Library/opening-hours/opening-hours.scss
Jira: [DDFFORM-417](https://reload.atlassian.net/browse/DDFFORM-417)
This PR depends on two PRs. 
[React PR](https://github.com/danskernesdigitalebibliotek/dpl-react/pull/1076)
[CMS PR](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/937)
This PR adds the markup and styling for the OpeningHours component, which is used to display the opening hours for a branch. 
I have left chromatic unaccepted on purpose. Will accept once approved. 
I am not sure why there are  34 UI changes. 
The only changes that _should_ be related to this pr, are the New Stories for openingHours in chromatic. 
Please add comments if you have any suggestions for improvement. 
This PR had a lot of refactoring after developing the React part. If you see any unused CSS or unnessecary markup mark it, although …
=> DDFFORM 417

src/stories/Blocks/header/header-sticky.js, src/styles/scss/shared.scss
We cant really reflect the overflow hidden change in the design system, as we have no story that combines the header, page etc, but it needs to be set on the div that wraps around all the content.
On CMS, where all the elements are combined, you are current allowed to zoom out way further than you should on mobile.
=> Make sure header doesnt break out zoom on mobile. DDFFORM-517

src/stories/Library/rich-text/RichText.tsx, src/stories/Library/rich-text/rich-text.scss
There is no design on this element, but if we add nothing, then there is no visual indication that this is a blockquote. This just adds a very simple, visual indicator.
https://reload.atlassian.net/browse/DDFFORM-492
=> Super simple blockquote design, for rich-text. DDFFORM-492

src/stories/Blocks/patron-page/ContactInfoSection.tsx, src/stories/Blocks/patron-page/PatronPage.stories.tsx, src/stories/Blocks/patron-page/PatronPage.tsx, src/stories/Blocks/patron-page/PatronPageSkeleton.tsx, src/stories/Blocks/status-loans/statusLoans.stories.tsx, src/stories/Blocks/status-loans/statusLoans.tsx, src/stories/Blocks/status-userprofile/statusUserprofile.stories.tsx, src/stories/Library/patron-info/PatronInfo.stories.tsx, src/stories/Library/patron-info/PatronInfoSkeleton.tsx
https://reload.atlassian.net/browse/DDFLSBP-486
Based on the version of the Patron page from the dpl-react project, I have constructed a Patron page with an accompanying skeleton. Some decisions were made to reuse parts of dpl-react where immediately possible, but also to use components from the design system where they already existed, instead of the version that emerged in dpl-react.
*
=> Add Patron page and skeleton [DDFLSBP-486]

src/stories/Blocks/advanced-search/advanced-search.scss, src/stories/Library/Buttons/row-button/row-button.scss, src/stories/Library/Lists/list-reservation/list-reservation.scss, src/stories/Library/Modals/modal-facet-browser/facet-browser.scss, src/stories/Library/Modals/modal-find-on-shelf/ModalFindOnShelf.tsx, src/stories/Library/card-list-page/facet-line.scss, src/stories/Library/footer-accordions/footer-accordions.scss, src/stories/Library/tag/tag.scss
https://reload.atlassian.net/browse/DDFLSBP-504
Corrects the issue where, in iOS 15 and later, if no color is specified in CSS for the button element, the text color defaults to blue. As a side effect, buttons defined in Figma to have the color #484848 now display the correct color in other browsers as well, where previously they defaulted to #000, the standard when no color is specified.
Fixed for:
- Footer
- Advanced Search
- Search Result Page
- Buttons / RowButton
- Lists / ReservationsAndLoans
- Modals / Facet browser
- Tag / Tag Button
=> Fix iOS 15 and later blue button text color [DDFLSBP-504]

src/stories/Library/Heros/hero/hero.scss
https://reload.atlassian.net/browse/DDFFORM-491
Long words in the hero title can disrupt the page layout. To address this issue, I have applied the `word-break: break-word` property to enhance layout stability and ensure text remains within its container. We can consider whether this should be inside `typography($typo__h1)`
=> Apply `word-break: break-word` CSS property to hero title

src/stories/Library/card-list-page/facet-line.scss
https://reload.atlassian.net/browse/DDFLSBP-518
This PR makes the filter facet line horizontally scrollable on mobile in one line in order to save space on smaller devices.
Mobile:
https://github.com/danskernesdigitalebibliotek/dpl-design-system/assets/28546954/267455f3-788e-4910-91f1-029c8629225d
Desktop (stays the same):
-
=> Fix inteligent facets on mobile devices

src/styles/scss/reset.scss
https://reload.atlassian.net/browse/DDFFORM-486
Reset css for `address` elements in `reset.scss`
This is needed in: https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1000
=> Reset css for `address` elements in `reset.scss`

base.scss, src/stories/Library/filtered-event-list/FilteredEventList.stories.tsx, src/stories/Library/filtered-event-list/FilteredEventListData.tsx, src/stories/Library/filtered-event-list/FilteredEventlist.tsx, src/stories/Library/filtered-event-list/filtered-event-list.scss, src/stories/Library/tag/tag-list/TagList.tsx, src/stories/utils/show-more.js, src/stories/utils/show-more.md
[DDFFORM-69](https://reload.atlassian.net/browse/DDFFORM-69)
This PR depends on a PR in the design system : https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1002
This PR adds the markup for the new component "Filtered event list". 
- Add component, story, test data and css for filtered event list. 
- extend/refactor `show-more.js` logic with more functionality for controlling wheter a button should be displayed or not after a list is expanded. Moved some namings/data-attributes around. 
Comment on this logic and test it out please. 
- Update existing components using `show-more.js` logic. Currently this should only be `<TagList/>`. If you think this is incorrect comment it. 
Chromatic is left unaccepted on purpose to see changes. Will accept once approved. 
Once again, we see …
=> DDFFORM 69

src/stories/Blocks/header/Header.tsx
https://reload.atlassian.net/browse/DDFLSBP-551
This PR adds "Login" text under the user icon when user isn't logged in, and "Liked" under the heart icon in the nav menu.
[Sibling PR in dpl-react](https://github.com/danskernesdigitalebibliotek/dpl-react/pull/1141)
[Sibling PR in dpl-cms](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1028)
=> Add text under login and favorites

base.scss, src/stories/Library/status-message/StatusMessage.stories.tsx, src/stories/Library/status-message/StatusMessage.tsx, src/stories/Library/status-message/status-message.scss
https://reload.atlassian.net/browse/DDFLSBP-528
When the user submits a webform, the submission notification status message was not styled. Thus I created a new story for status-messages. It largely resembles the error-message styling, but using the icon-check instead of icon-warning.
Design system: short message:
Design system: long message:
=> DDFLSBP-528/add status message story and styling for succesful webform submission

base.scss, src/stories/Library/event-list-stacked/EventListStacked.tsx, src/stories/Library/event-list-stacked/event-list-stacked.scss, src/stories/Library/event-list-stacked/eventListStacked.stories.tsx
[DDFFORM-126](https://reload.atlassian.net/browse/DDFFORM-126)
Related CMS PR https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1054
This PR adds a component and styling for "event-list-stacked". 
This is a similar view to the stacked events used on /events, but this will be used on eventseries pages to display the individual instances in the series as a temporary solution. 
Look away form the chromatic changes that are not related to the newly introduced component.
[DDFFORM-126]: https://reload.atlassian.net/browse/DDFFORM-126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add EventListStacked component.

base.scss, src/stories/Blocks/create-patron/CreatePatron.stories.tsx, src/stories/Blocks/create-patron/CreatePatron.tsx, src/stories/Blocks/create-patron/create-patron.scss, src/stories/Library/Forms/input/DoubleInputRow.tsx, src/stories/Library/Forms/input/Input.tsx, src/stories/Library/Forms/input/input.scss, src/stories/Library/dropdown/Dropdown.tsx, src/stories/Library/dropdown/dropdown.scss, src/stories/Library/patron-info/patron-info.scss
https://reload.atlassian.net/browse/DDFLSBP-563
https://reload.atlassian.net/browse/DDFLSBP-594
This PR introduces the Create Patron story, and updates some styling connected to form elements.
[Sibling PR](https://github.com/danskernesdigitalebibliotek/dpl-react/pull/1150)
=> User registration form v2

src/stories/Blocks/header/Header.tsx, src/stories/Blocks/header/header.scss, src/stories/Library/footer-widgets/FooterWidgets.tsx, src/stories/Library/logo/Logo.stories.tsx, src/stories/Library/logo/Logo.tsx, src/stories/Library/logo/logo.scss
PR dækker to tickets: 
[DDFFORM-696](https://reload.atlassian.net/browse/DDFFORM-696)
[DDFFORM-709](https://reload.atlassian.net/browse/DDFFORM-709)
Depends on PR in cms: https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1099
This PR refators the logo markup/css. 
The component should now be updated to handle the redirect to frontpage, include an aria-label as requested in [DDFFORM-709](https://reload.atlassian.net/browse/DDFFORM-709), and display the image/ fallback of library name and place accordingly. 
I have left the UI changes unaccepted until reviewed.
[DDFFORM-696]: https://reload.atlassian.net/browse/DDFFORM-696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DDFFORM-709]: …
=> Refactor logo into logo-link

src/stories/Library/Lists/list-description/ListDescription.tsx, src/stories/Library/Lists/list-description/ListDescriptionFakeData.tsx, src/stories/Library/Lists/list-description/list-description.scss
https://reload.atlassian.net/browse/DDFLSBP-543
Added 'list' type to ListDescription for rendering content descriptions, such as track listings.
=> Added list type to ListDescription values [DDFLSBP-543]

src/stories/Library/nav-grid/init-nav-grid.js
https://reload.atlassian.net/browse/DDFFORM-612
This pull request ensures that the next item link in the `nav-grid` receives focus after the "show more" button is clicked.
https://github.com/danskernesdigitalebibliotek/dpl-design-system/assets/49920322/847b75e1-ac7c-4335-b7be-2209082ade20
=> Add focus on next item after "show more" click in `nav-grid`

src/stories/Blocks/header/Header.tsx, src/stories/Blocks/header/header.scss
https://reload.atlassian.net/browse/DDFLSBP-636
Animate advanced search header dropdown icon on click to indicate state and make it crisp.
https://github.com/danskernesdigitalebibliotek/dpl-design-system/assets/28546954/e519bdc5-0329-4b0c-b0af-c17ca8e1fefe
[Sibling PR](https://github.com/danskernesdigitalebibliotek/dpl-react/pull/1236)
=> Advanced search header dropdown

.github/workflows/chromatic.yml
We have seen Chromatic failing with the following error. This apparently occurs after updating to versio 11.5 of the GitHub Action. Examples include:
- https://github.com/danskernesdigitalebibliotek/dpl-design-system/actions/runs/9343042365/job/25724060490?pr=652
- https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/653
- https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/651
This was the last PR when it did not fail. It uses v11.4 of the Chromatic action:
- https://github.com/danskernesdigitalebibliotek/dpl-design-system/actions/runs/9317798995/job/25648839916?pr=650
Try to lock it at 11.4 to address this. Dependabot should help us update in the future.
Error: error:0308010C:digital envelope routines::unsupported
at new Hash …
=> Lock Chromatic GitHub action to 11.4

.github/workflows/create-cms-pr.yml, .github/workflows/create-release-on-branch-changes.yml
https://reload.atlassian.net/browse/DDFLSBP-643
This PR adds a Github Workflow `create-cms-pr` that requests [dpl-cms to create a PR](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1158).
For separation of concerns the workflow is triggered by the `create-release-on-branch-changes` workflow. In that way we try to avoid leaving all steps in the `create-release-on-branch-changes` and isolate the remote pr action steps in a separate yml file.
The changes here are similar to the changes in the [dpl-react repo](https://github.com/danskernesdigitalebibliotek/dpl-react/pull/1208).
We need to set secrret and variables similiar to what has been set in:
https://github.com/reload/poc-dpl-design-system-pr-trigger
=> Add workflow that creates a pr externally in the dpl-cms repo

src/stories/Library/Forms/input/Input.stories.tsx, src/stories/Library/Forms/input/Input.tsx, src/stories/Library/Forms/input/input.scss, src/stories/Library/Forms/textarea/textarea.scss
https://reload.atlassian.net/browse/DDFLSBP-631
Enhanced accessibility by increasing input and textarea contrast (and also fixed Input component re-renders and clsx class assignment in Storybook)
=> Enhance accessibility of input and textarea fields [DDFLSBP-631]

src/stories/Blocks/header/Header.tsx, src/stories/Blocks/header/header.scss, src/stories/Library/header-sidebar-nav/header-sidebar-nav.scss
- **Ensure that burgermenu is not hidden when desktop is hidden.**
- **Ensure sidebar menu items do not overflow container.**
Jira : [DDFFORM-812](https://reload.atlassian.net/browse/DDFFORM-812)
cms pr: https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1246
This PR aims to ensure that the header-sidebar-nav(Menu toggled by the burgermenu) is shown, when the current menu being displayed on the site is the burgermenu. 
Whenever the burgermenu is displayed and toggled/clicked, it should now shown the menu. 
Also added a change to menu items cant overflow the sidebar container.
If chromatic is failing it should be unrelated to the issue.
[DDFFORM-812]: https://reload.atlassian.net/browse/DDFFORM-812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS …
=> DDFFORM 812 burger menu

src/stories/Library/material-grid/MaterialGrid.stories.tsx, src/stories/Library/material-grid/MaterialGrid.tsx, src/stories/Library/material-grid/material-grid.scss
Jira ticket: [DDFFORM-520](https://reload.atlassian.net/browse/DDFFORM-520)
React pr: https://github.com/danskernesdigitalebibliotek/dpl-react/pull/1238
CMS pr: https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1198
This PR updates the mark and css for the material grid component with a new prop for displaying a description for the material grid. 
[DDFFORM-520]: https://reload.atlassian.net/browse/DDFFORM-520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add "Description" for materialgrid.

admin-base.scss, base.scss, package.json, src/stories/Library/cover/Cover.tsx, src/stories/Library/cover/cover.scss, src/stories/Library/cover/types.ts, src/stories/Library/material-search/MaterialSearch.stories.tsx, src/stories/Library/material-search/MaterialSearch.tsx, src/stories/Library/material-search/MaterialSearchExampleData.ts, src/stories/Library/material-search/MaterialSearchInputs.tsx, src/stories/Library/material-search/MaterialSearchList.tsx, src/stories/Library/material-search/MaterialSearchLoading.tsx, src/stories/Library/material-search/MaterialSearchPreview.tsx, src/stories/Library/material-search/material-search.scss
Ticket: [DDFFORM-611](https://reload.atlassian.net/browse/DDFFORM-611)
This PR Depends on: 
React PR: https://github.com/danskernesdigitalebibliotek/dpl-react/pull/1223
CMS PR: https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1169
This PR introduces the markup and styling for MaterialSearch, a component that will be used to allow searching for materials and selecting them for display in the admin interface for paragraphs using the the work_id field with the new field widget. Currently this is Recommandation and MaterialGridManual. 
You can either go commit by commit or view it as a whole. 
Consider the introduction of admin-base css and comment if there are any relevant details i have missed. 
Consider both the comment and approach in the css file regarding covers. 
Remember to …
=> DDFFORM 611 backend anbefalings komp

src/stories/Library/warning-status/warning-status.scss
https://reload.atlassian.net/browse/DDFLSBP-679
Adjust layout for .warning-bar component for smaller screens and refactored to use nested selectors following the BEM methodology.
=> Adjust layout for .warning-bar component for smaller screens [DDFLSBP-679]

src/stories/Library/opening-hours/opening-hours.scss
https://reload.atlassian.net/browse/DDFFORM-862
Add tags style to week display in opening hours due to the design: https://www.figma.com/design/Zx9GrkFA3l4ISvyZD2q0Qi/Designsystem?node-id=7486-63527&t=9ySgYMKGTKS2auc9-4
http://varnish.pr-1329.dpl-cms.dplplat01.dpl.reload.dk/hovedbiblioteket
=> Add tags style to week display in opening hours

src/stories/Library/rich-text/rich-text.scss, src/styles/scss/tools/variables.typography.scss
[Figma Design System](https://www.figma.com/design/Zx9GrkFA3l4ISvyZD2q0Qi/Designsystem?node-id=15296-51574&t=xFP5EmqluakmKgeF-4)
https://reload.atlassian.net/browse/DDFFORM-399
This pull request refactors the CSS for blockquotes in the `rich-text.scss` file to align with the new design specifications. The following changes have been made:
- Added a new typography variable `$typo_quotes`.
- Updated the CSS for `blockquote` elements to align with the new design
http://varnish.pr-1334.dpl-cms.dplplat01.dpl.reload.dk/artikler/test-citat
=> Refactor blockquote CSS in `rich-text.scss`

base.scss, public/icons/basic/icon-underlined.svg, src/stories/Library/banner/Banner.stories.tsx, src/stories/Library/banner/Banner.tsx, src/stories/Library/banner/banner.scss, src/styles/scss/tools/mixins.tools.scss
https://reload.atlassian.net/browse/DDFFORM-540
This pull request adds a new `banner` component that contains a required link and title. It can be used with a description and a background image to enhance visual appeal.
The `title` field is a `ReactNode` where the <u> (underline) tag has a custom underlined SVG placed beneath it.
=> Add new `banner` component

src/stories/Library/material-search/Errors/ErrorState.ts, src/stories/Library/material-search/Errors/MaterialSearchBaseError.tsx, src/stories/Library/material-search/Errors/MaterialTypeNotFoundError.tsx, src/stories/Library/material-search/Errors/WorkNotFoundError.tsx, src/stories/Library/material-search/MaterialSearch.stories.tsx, src/stories/Library/material-search/MaterialSearch.tsx, src/stories/Library/material-search/MaterialSearchPreview.tsx, src/stories/Library/material-search/material-search.scss
- **Add error components for material search.**
- **Add css for material search error components.**
[DDFFORM-900](https://reload.atlassian.net/browse/DDFFORM-900)
[React pr](https://github.com/danskernesdigitalebibliotek/dpl-react/pull/1304)
[CMS PR](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1310)
This PR introduceres error/warning components to the material search component. 
They are used to display errors in retrieving the material that was saved before. 
[DDFFORM-900]: https://reload.atlassian.net/browse/DDFFORM-900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DDFFORM 900 material warning backend

src/stories/Library/cover/Cover.tsx, src/stories/Library/cover/types.ts
https://reload.atlassian.net/browse/DDFFORM-719
https://github.com/danskernesdigitalebibliotek/dpl-react/pull/1313
This pull request introduces the isHiddenFromScreenReaders property to the Cover component to ensure alignment with the updates made in https://github.com/danskernesdigitalebibliotek/dpl-react/pull/1313.
The design system does not have an equivalent Link component, so this addition is exclusive to the Cover component.
We don't have the same `Link` component in the design system therefore it's only added in the `Cover` component
=> Add `isHiddenFromScreenReaders` to `Cover`

src/stories/Library/material-header/material-periodical-select.scss, src/styles/scss/tools/placeholder.scss
When using an inline SVG it must be encoded. Otherwise browsers may choke on it due to unescaped characters like < and ".
At the moment problem can be seen when the Chromatic/Cypress integration tries to generate pages with inline CSS. Without this process fails and CSS is never loaded.
To address this we encode the inline CSS using
https://yoksel.github.io/url-encoder/. A proper SCSS function to address this would be preferable but I could not find such a thing.
We only have a few actual instances of inline SVGs to for now it should be OK to just change these.
This is needed for danskernesdigitalebibliotek/dpl-cms#1333
=> Encode inline SVGs

src/stories/Library/dropdown/dropdown.scss, src/stories/Library/multiselect/multiselect.scss
https://reload.atlassian.net/browse/DDFLSBP-685
Removed text-transform: capitalized and added text-transform: none on dropdown and multiselect elements.
This is done to make it consistent throughout the website and on all browser/operation systems, as there are some differences between the way MacOS and Windows show dropdowns. It also adds to the readability of the dropdown and multiselect elements.
Advanced search example:
Contact form with dropdown element example:
This PR has a sister PR in dpl-cms: https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1385
=> DDFLSBP-685 - Remove uppercase on dropdown and multiselect elements

src/stories/Library/input-label/InputLabel.stories.tsx, src/stories/Library/input-label/InputLabel.tsx, src/stories/Library/input-label/input-label.scss
https://reload.atlassian.net/browse/DDFLSBP-659
Added styling for required fields. We simply add a new class `.form-required::after` containing an asterisk ( *). The class is added on fields where the input field is required to be filled out.
Showing the contact webform with required fields:
This PR has a sister PR in dpl-cms: https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1363
This PR has a sister PR in dpl-react: https://github.com/danskernesdigitalebibliotek/dpl-react/pull/1327
=> DDFLSBP-659 - Add visual indicators on required fields

.stylelintrc, admin-base.scss, base.scss, src/stories/Blocks/header/Header.tsx, src/stories/Blocks/header/header.scss, src/stories/Library/dialog/Dialog.tsx, src/stories/Library/dialog/dialog.scss, src/stories/Library/disclosure-controllable/DisclosureControllable.tsx, src/stories/Library/opening-hours-editor/opening-hours-editor.scss, src/stories/Library/opening-hours-sidebar/OpeningHoursSidebar.stories.tsx, src/stories/Library/opening-hours-sidebar/OpeningHoursSidebar.tsx, src/stories/Library/opening-hours-sidebar/OpeningHoursSidebarDetails.tsx, src/stories/Library/opening-hours-sidebar/OpeningHoursSidebarSummary.tsx, src/stories/Library/opening-hours-sidebar/OpeningHoursSidebarWithDialog.stories.tsx, src/stories/Library/opening-hours-sidebar/opening-hours-libraries-data.ts, src/stories/Library/opening-hours-sidebar/opening-hours-sidebar.scss
[DDFFORM-822](https://reload.atlassian.net/browse/DDFFORM-822)
This pull request introduces new `OpeningHoursSidebar` stories for inspecting layout and animation. Additionally, it refactors the `Dialog` component to support sidebar functionality, enhancing the overall flexibility and usability of the dialog system.
I want to use our dialog component as much as possible for accessibility and reduction of JavaScript. However, there are some limitations related to CSS (so far). But I have arrived at a satisfactory result. I had to ignore some CSS linting rules because they do not include the latest CSS features.
<s>I know that Firefox doesn't support @starting-style for display: none (yet). In this case, the animation won't work. However, I believe there are advantages in using simpler HTML, …
=> Ddfform 822 modal til abningstider

package.json, src/stories/Library/Modals/modal-pause/modal-pause.scss, src/stories/Library/date-calendar/date-calendar.scss, yarn.lock
https://reload.atlassian.net/browse/DDFBRA-52
This PR fixes an issue where the date picker for pausing reservations was bleeding outside the screen on small devices. It is possible to scroll, but the users couldn't figure it out because one needs to scroll inside the date picker overlay window. But now they should be able to see the whole window at all times.
AFTER:
BEFORE:
-
=> Fix "pause reservations" popup

src/stories/Library/Modals/modal.scss
https://reload.atlassian.net/browse/DDFHER-96
This pull request adds `@media print` CSS styles to our modal component to enable proper printing of articles displayed within modals. While this solution addresses the immediate issue, we might want to consider using a library like `react-to-print` for a more beautiful approach in the future.
[print.pdf](https://github.com/user-attachments/files/17375746/print.pdf)
https://varnish.pr-1657.dpl-cms.dplplat01.dpl.reload.dk/work/work-of%3A870971-avis%3A89724244?type=artikel&modal=infomedia-modal-870971-avis%3A89724244
=> DDFHER-96 - Add `@media print` to enable printing of articles in modals

.github/dependabot.yml
We want to ensure that React and React DOM is updated in parallel.
This is especially relevant for React 19.
=> Add a Dependabot group for React dependencies

src/stories/Library/Modals/modal.scss, src/stories/Library/dialog/dialog.scss
https://reload.atlassian.net/browse/DDFBRA-225
Ensures a more consistent layout on mobile devices by accounting for dynamic changes in viewport height caused by browser UI elements, such as the address bar in Chrome.
https://varnish.pr-1877.dpl-cms.dplplat01.dpl.reload.dk/
https://github.com/user-attachments/assets/f07bf82e-b125-453c-b36f-f4e8e60b705e
=> DDFBRA-225 - Use `svh` height to ensure consistent modal layout

src/stories/Library/dialog/dialog.scss, src/stories/Library/opening-hours-sidebar/OpeningHoursSidebar.stories.tsx, src/stories/Library/opening-hours-sidebar/opening-hours-libraries-data.ts
https://reload.atlassian.net/browse/DDFBRA-401
The previous use of `min-height` led to an unexpected layout issue, preventing the branch list from displaying correctly and making scrolling impossible.
**Before:**
**After**
With few:
with many:
On mobile: 
Video:
https://github.com/user-attachments/assets/1e0c14f5-8d8a-4502-a922-44af49f5c498
https://varnish.pr-2003.dpl-cms.dplplat01.dpl.reload.dk/
=> DDFBRA-401 - Fix Release 2025.4.0 - Replace `min-height` with `height` in `dialog--sidebar`

src/stories/Library/date-calendar/date-calendar.scss
https://reload.atlassian.net/browse/DDFBRA-364
It seems the previous CSS rule was targeting a too small device size, as many phones are larger than 375px. 
I also tweaked the CSS, so the calendar is centered horizontally. 
As for the issue with scrolling, it should have been fixed in #809
=> Center calendar horizontally on mobile and hide box arrow

base.scss, src/stories/Blocks/page/Page.stories.tsx, src/stories/Blocks/page/Page.tsx, src/stories/Blocks/page/page.scss
DDFFSAL-73
[DDFSAL-73](https://reload.atlassian.net/browse/DDFSAL-73)
CMS PR: https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2214
This PR adds a class for wrapping tags on pages & provides an example usage. 
See the new example with a page using tags
[DDFSAL-73]: https://reload.atlassian.net/browse/DDFSAL-73?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add a wrapper classes for tags used on pages / article html tags.

.github/workflows/create-release-on-branch-changes.yml, .github/workflows/create-release-on-tag.yml
https://reload.atlassian.net/browse/DDFBRA-703
There is a bug with version `2.3.0` of `softprops/action-gh-release`. The solution I found on GitHub is to temporarily switch to a specific commit of the action.
This pull request updates the GitHub Actions workflows to use a specific commit hash for the `softprops/action-gh-release` action, instead of relying on the `v2` version tag.
Refs:
- https://github.com/softprops/action-gh-release/issues/627
- https://github.com/softprops/action-gh-release/issues/628
=> Use action-gh-release version v2.2.2

src/stories/Blocks/advanced-search/AdvancedSearch.stories.tsx, src/stories/Blocks/advanced-search/AdvancedSearch.tsx, src/stories/Blocks/advanced-search/advanced-search.scss, src/stories/Library/Forms/checkbox/Checkbox.tsx, src/stories/Library/Forms/input/Input.tsx, src/stories/Library/Forms/textarea/Textarea.tsx
https://reload.atlassian.net/browse/DDFSAL-92
Originally, the link was intended to be placed under the title. However, this caused spacing issues when toggling between CQL and Advanced Search modes. Therefore, the link is now placed below the CQL textfeild.
To ensure it aligns correctly under the CQL textfeild without being affected by grid gaps, it has been wrapped in a separate div.
**AI:**
This pull request enhances the `AdvancedSearch` component by adding support for an external help link when CQL search is enabled. The changes include updates to the component's props, story configuration, and rendering logic.
* **Support for external help link text:**
- Added a new prop `cqlSearchExternalHelpLinkText` to the `AdvancedSearchProps` interface and included it in the component's props. …
=> DDFSAL-92 - Enhance styling in advance search + Add CQL help link
