danskernesdigitalebibliotek/dpl-design-system

- .github/workflows/lint.yml
- .markdownlint-cli2.yaml
- README.md
- Taskfile.yml
- docker-compose.mac-nfs.yml
- docker-compose.yml
- package-lock.json
- package.json
* Added docker compose setup
* Added go-tasks
* Updated story book to use port 80
* Added markdown lint and fixed readme file
> Streamline to match the other repos

- Taskfile.yml
Otherwise NFS support will not be added and chokidar polling not
defined. This will result in poorer filesystem performance.
> Specify Docker compose files when starting a development environment

- README.md
- Taskfile.yml
- base.scss
- package-lock.json
- src/stories/autosuggest-text/AutosuggestText.stories.tsx
- src/stories/autosuggest-text/AutosuggestText.tsx
- src/stories/autosuggest-text/autosuggest-text.scss
- src/stories/availability-label/availability-label.scss
- src/stories/button-favourite/ButtonFavourite.stories.tsx
- src/stories/button-favourite/ButtonFavourite.tsx
- src/stories/button-favourite/button-favourite.scss
- src/stories/checkbox/Checkbox.stories.tsx
- src/stories/checkbox/Checkbox.tsx
- src/stories/checkbox/checkbox.scss
- src/stories/header/Header.stories.tsx
- src/stories/header/Header.tsx
- src/stories/header/header.scss
- src/stories/icon/icon-favourite/IconFavourite.stories.tsx
- src/stories/icon/icon-favourite/IconFavourite.tsx
- src/stories/icon/icon-favourite/icon-favourite.scss
- src/stories/list-materials/ListMaterials.tsx
- src/stories/search-result-item/SearchResultItem.stories.tsx
- src/stories/search-result-item/SearchResultItem.tsx
- src/stories/search-result-item/search-result-item.scss
Combined release 1 PR - await cache errors
> Release 1 - PR

- base.scss
- src/stories/Library/reservation-header/ReservationHeader.stories.tsx
- src/stories/Library/reservation-header/ReservationHeader.tsx
- src/stories/Library/reservation-header/reservation-header.scss
> 5381: reservation header added

- src/stories/Library/horizontal-term-line/horizontal-term-line.scss
This is a small PR to correct a css mistake I made in previous work
> Change css flex wrap for horizontal-term-line

- src/stories/Library/Modals/modal-loan/ModalLoan.stories.tsx
- src/stories/Library/Modals/modal-loan/ModalLoan.tsx
- src/stories/Library/Modals/modal-loan/modal-loan.scss
- src/styles/scss/shared.scss
> 5389: created fixed buttons in bottom of page

- src/stories/Library/Lists/list-reservation/ListReservationsAndLoans.tsx
- src/stories/Library/Lists/list-reservation/list-reservation.scss
I restyled this, as it is not a link but a button.
> 5389: style button as link

- src/stories/Library/typography/Typography.tsx
- src/stories/Library/typography/typography.scss
Adding a utitlity class for truncating text
> Class for text truncation

- base.scss
- src/stories/Library/Modals/modal-login/ModalLogin.stories.tsx
- src/stories/Library/Modals/modal-login/ModalLogin.tsx
- src/stories/Library/Modals/modal-login/modal-login.scss
- src/styles/scss/shared.scss
> Modal login

- base.scss
- src/stories/Library/Modals/modal-header/ModalHeader.stories.tsx
- src/stories/Library/Modals/modal-header/ModalHeader.tsx
- src/stories/Library/Modals/modal-header/modal-header.scss
- src/stories/Library/Modals/modal-profile/ModalProfile.stories.tsx
- src/stories/Library/Modals/modal-profile/ModalProfile.tsx
- src/stories/Library/Modals/modal-profile/modal-profile.scss
- src/stories/Library/avatar/Avatar.stories.tsx
- src/stories/Library/avatar/Avatar.tsx
- src/stories/Library/avatar/avatar.scss
- src/styles/scss/shared.scss
Add user profile menu in modal with seperate components for avatar, modal header and the profile modal itself.
> Modal profile menu

- src/stories/Library/Lists/list-dashboard/ListDashboard.stories.tsx
- src/stories/Library/Lists/list-dashboard/ListDashboard.tsx
- src/stories/Library/Lists/list-dashboard/list-dashboard.scss
- src/stories/Library/Modals/modal-profile/ModalProfile.tsx
https://platform.dandigbib.org/issues/5388
Make list-dashboard clickable and apply :hover styling.
> 5388: Add link function and hover

- base.scss
- src/stories/Blocks/status-userprofile/status-userprofile.scss
- src/stories/Blocks/status-userprofile/statusUserprofile.stories.tsx
- src/stories/Blocks/status-userprofile/statusUserprofile.tsx
https://platform.dandigbib.org/issues/5388
Add component with Loans and Reservation status lists
State with data:
Empty state:
> Loans and reservations status

- src/stories/Blocks/material-manifestation-item/MaterialMainfestationItem.tsx
- src/stories/Blocks/material-manifestation-item/material-manifestation-item.scss
This PR is a css rename for material-manifestation-item to follow standards and guidelines for BEM
> Change to follow guidelines for BEM

- src/stories/Library/Lists/list-empty/ListEmpty.stories.tsx
- src/stories/Library/Lists/list-empty/ListEmpty.tsx
- src/stories/Library/Lists/list-empty/list-empty.scss
https://platform.dandigbib.org/issues/5396
This pr add the possibility of displaying additional links in the list-empty component
> Links in list empty

- base.scss
- src/stories/Library/Forms/input/Input.stories.tsx
- src/stories/Library/Forms/input/Input.tsx
- src/stories/Library/Forms/input/input.scss
> 5398: add input with validation

- src/stories/Blocks/reservation/Reservation.tsx
- src/stories/Blocks/reservation/reservation.scss
- src/stories/Blocks/reservation/reservation.stories.tsx
- src/stories/Library/reservation/ReservationError.tsx
- src/stories/Library/reservation/ReservationSucces.tsx
https://www.figma.com/file/ETOZIfmgGS1HUfio57SOh7/S%C3%B8gning?node-id=982%3A13337
> Add ReservationSucces + ReservationError

- .vscode.example/dpl-design-system.code-snippets
- .vscode.example/extensions.json
- src/stories/Blocks/reservation/forms/Collect.tsx
- src/stories/Blocks/reservation/forms/Email.tsx
- src/stories/Blocks/reservation/forms/Expiration.tsx
- src/stories/Blocks/reservation/forms/Form.tsx
- src/stories/Blocks/reservation/forms/Sms.tsx
- src/stories/Blocks/reservation/forms/form.stories.tsx
- src/stories/Blocks/reservation/reservation.scss
- src/stories/Blocks/reservation/reservation.stories.tsx
- src/stories/Library/Buttons/button/Button.tsx
- src/stories/Library/Buttons/button/buttons.scss
- src/stories/Library/Forms/input/Input.tsx
https://reload.atlassian.net/browse/DDFSOEG-210
A story that show the composition of the various user input forms in the reservation flow.
Validation handling need to be decided upon. This will have an impact on how we choose to structure the DOM and naming the classes.
> Reservation forms

- .github/workflows/deployment.yml
- .markdownlint-cli2.yaml
- README.md
Using this project as an npm package including workflows with forks can be tricky.
This tries to improve the documentation.
> Improve release docs

- src/stories/Library/Icons/icon-favourite/icon-favourite.scss
- src/stories/Library/colors/color-variables.scss
Fix chromium errors, the tints were gone - now readded by reverting.
> revert color change

- src/stories/Library/Lists/list-reservation/list-reservation.scss
- src/stories/Library/loan-list-page/loan-list-page.scss
https://platform.dandigbib.org/issues/5548
Fix margin between elements
Fix font size
> 5548: fix margin, padding and fontsizes

- src/stories/Library/Forms/input/input.scss
- src/stories/Library/patron-info/patron-info.scss
wrap input style in classes
n/a
> 5398: wrap input css in patron__input

- .github/workflows/gh-pages.yml
- src/stories/Library/search-result-item/search-result-item.scss
While we have projects in the development phase we would like to have it updated regularly
> Build GH storybook from develop

- .github/workflows/gh-pages.yml
This PR ensures that pushes to develop are actually deployed to GitHub Pages as intended.
Please check the individual commits for more commentary.
Chromatic identified 8 changes unrelated to this change. They seem to be from #177 where Chromatic got confused about  accepted changes.
> Publish Storybook to GitHub Pages on Develop

- src/stories/Library/Modals/modal-loan/modal-loan.scss
https://platform.dandigbib.org/issues/
The buttons should align with the container 
> 5608: add padding to buttons (also bemify)

- src/stories/Library/recommender/Recommender.stories.tsx
- src/stories/Library/recommender/Recommender.tsx
- src/stories/Library/recommender/recommender.scss
n/a
Update scss to make it possible to allow no padding and four items.
https://616ffdab9acbf5003ad5fd2b-thfaxyvbum.chromatic.com/?path=%2Fstory%2Flibrary-recommender--something-similar
https://616ffdab9acbf5003ad5fd2b-thfaxyvbum.chromatic.com/?path=%2Fstory%2Flibrary-recommender--recommend
> Itkdev - CMN-541: update css in recommender/somethinglikethis

- src/stories/Library/Modals/modal-login/modal-login.scss
https://platform.dandigbib.org/issues/5716 <- fixing that made this necessary
Made modal look as it used to, even though it now uses the proper modal component
> itkdev: update styling to work with modal

- src/stories/Blocks/status-userprofile/status-userprofile.scss
- src/stories/Blocks/status-userprofile/statusUserprofile.tsx
- src/stories/Library/Lists/list-empty/list-empty.scss
https://platform.dandigbib.org/issues/5374
- remove height from empty list
- align notification columns baseline
n/a
n/a
> itkdev: dashboard styling

- src/stories/Library/Modals/modal-login/ModalLogin.tsx
- src/stories/Library/Modals/modal-login/modal-login.scss
- src/stories/Library/Modals/modal-profile/ModalProfile.tsx
- src/stories/Library/Modals/modal-profile/modal-profile.scss
https://platform.dandigbib.org/issues/5715
Menu styling + update storybook entry
n/a
> ITKDEV - 5715 - semantic menu

- src/stories/Blocks/header/header.scss
- src/stories/Blocks/status-userprofile/status-userprofile.scss
- src/stories/Blocks/status-userprofile/statusUserprofile.tsx
- src/stories/Library/Lists/list-empty/ListEmpty.tsx
- src/stories/Library/Lists/list-materials/ListMaterials.tsx
- src/stories/Library/Lists/list-materials/list-materials.scss
- src/stories/Library/Lists/list-reservation/ListReservationsAndLoans.stories.tsx
- src/stories/Library/Lists/list-reservation/ListReservationsAndLoans.tsx
- src/stories/Library/Lists/list-reservation/list-reservation.scss
- src/stories/Library/Modals/modal-loan/ModalLoan.tsx
- src/stories/Library/Modals/modal-login/modal-login.scss
- src/stories/Library/typography/typography.scss
https://platform.dandigbib.org/issues/5568
Ellipsis on title overflows
https://616ffdab9acbf5003ad5fd2b-aniilymqtg.chromatic.com/?path=%2Fstory%2Flibrary-lists-reservationandloans--item-1 
https://616ffdab9acbf5003ad5fd2b-aniilymqtg.chromatic.com/?path=%2Fstory%2Flibrary-modals-loan--modal-loan-expired
n/a
> itkdev: Feature/5568 ellipsis on title

- src/stories/Blocks/header/header.scss
- src/stories/Blocks/status-userprofile/status-userprofile.scss
- src/stories/Blocks/status-userprofile/statusUserprofile.tsx
- src/stories/Library/Lists/list-empty/ListEmpty.tsx
- src/stories/Library/Modals/modal-login/modal-login.scss
n/a
- Make space for notifications
- Align user icon in header
- remove row-gap
n/a
n/a
> itkdev: menu style updates

- src/stories/Library/Modals/modal-login/modal-login.scss
- src/stories/Library/dashboard-page/dashboard-page.scss
- src/stories/Library/status-label/status-label.scss
n/a
status label more space on mobile
modal width 100% again
https://616ffdab9acbf5003ad5fd2b-fzgugzqdtu.chromatic.com/?path=%2Fstory%2Flibrary-status-label--danger
> itkdev: Feature/restore menu width

- src/stories/Library/Lists/list-materials/ListMaterials.stories.tsx
- src/stories/Library/Lists/list-materials/ListMaterials.tsx
- src/stories/Library/Modals/modal-loan/ModalLoan.tsx
- src/stories/Library/Modals/modal-loan/modal-loan.scss
- src/stories/Library/Modals/modal-text/modal-text.scss
- src/stories/Library/card-list-page/ResultPager.tsx
- src/stories/Library/card-list-page/result-pager.scss
https://platform.dandigbib.org/issues/5389
small alignments to make space for both pager/button
n/a
n/a
> 5389: positioning of pager/buttons fixed in bottom

- src/stories/Library/Modals/modal-loan/modal-loan.scss
- src/stories/Library/card-list-page/result-pager.scss
> itkdev: mobile view of group modal buttons

- src/stories/Blocks/header/header.scss
This PR adjusts the z-index of the search header dropdown, so that the menu opens on top of autosuggest, if autosuggest is open too.
> Search header dropdown

- base.scss
- src/stories/Blocks/article/Article.stories.tsx
- src/stories/Blocks/article/Article.tsx
- src/stories/Blocks/article/article.scss
- src/stories/Library/Buttons/row-button/RowButton.stories.tsx
- src/stories/Library/Buttons/row-button/RowButton.tsx
- src/stories/Library/Buttons/row-button/RowButtons.stories.tsx
- src/stories/Library/Buttons/row-button/RowButtons.tsx
- src/stories/Library/Buttons/row-button/row-button.scss
- src/stories/Library/Buttons/row-button/row-buttons.scss
- src/stories/Library/article-header/ArticleHeader.tsx
- src/stories/Library/article-header/article-header.scss
- src/stories/Library/links/arrow-link/ArrowLink.stories.tsx
- src/stories/Library/links/arrow-link/ArrowLink.tsx
- src/stories/Library/links/arrow-link/arrow-link.scss
https://reload.atlassian.net/browse/DDFFORM-3
This Pull Request introduces the necessary CSS and markup for the article page, including the article header and its sub-components.
- Addition of essential CSS for the article page layout.
- Implementation of markup for the article header.
- Implementation of sub-components used within the article header.
> Add CSS and stories for `Article`, `ArticleHeader`, `ArrowLink`, `RowButton`

- bundle.sh
- package.json
See commit comments for individual comments.
> Dapple support

- src/stories/Library/Lists/fee-list/fee-list.scss
- src/stories/Library/Modals/modal-loan/modal-loan.scss
https://reload.atlassian.net/browse/DDFLSBP-341
Stackable cards were not stacking on the fees list page.
n/a
n/a
> Make sure to show stackable cards on the fee-list-page

- base.scss
- src/stories/Blocks/event-page/EventPage.stories.tsx
- src/stories/Blocks/event-page/EventPage.tsx
- src/stories/Blocks/material-manifestation-item/MaterialMainfestationItem.stories.tsx
- src/stories/Library/Lists/list-description/ListDescription.tsx
- src/stories/Library/Lists/list-description/ListDescriptionFakeData.tsx
- src/stories/Library/Lists/list-description/list-description.scss
- src/stories/Library/event-description/EventDescription.tsx
- src/stories/Library/event-description/event-description.scss
- src/stories/Library/event-header/event-header.scss
https://reload.atlassian.net/browse/DDFFORM-17
This Pull Request adds the `EventDescription` component + Refactoring the `ListDescription` component. 
The refactor of `ListDescription` adjusts its capability to handle multiple values and modifies its CSS, introducing a BEM modifier for different visual presentation on the event page. 
The `EventDescription` component, now part of the `EventPage`, includes all necessary markup and CSS specific to the description section of events.
> Add `EventDescription` component + Refactor `ListDescription` component 

- .github/workflows/create-release-on-branch-changes.yml
- .github/workflows/create-release-on-tag.yml
Otherwise the zip step fails on branches/tags with "/" in it.
> Sluggify branch/tag name

- Taskfile.yml
- src/stories/Library/link-with-icon/link-with-icon.scss
- src/styles/scss/tools/mixins.misc.scss
> Fix SCS after merge conflict.

- base.scss
- src/stories/Library/rich-text/RichText.stories.tsx
- src/stories/Library/rich-text/RichText.tsx
- src/stories/Library/rich-text/rich-text.scss
- src/styles/scss/tools/placeholder.scss
- src/styles/scss/tools/variables.layout.scss
- src/styles/scss/tools/variables.typography.scss
This component is used for WYSIWYG content.
E.g. we cannot control classes of the underlying elements, so in
this case we will target HTML tags instead.
> Rich text / WYSIWYG styling. DDFFORM-5.

- src/styles/scss/reset.scss
a small update to our CSS to fix the aspect ratio of images on our site.
> Add `height: auto` to img Elements

- base.scss
- src/stories/Library/image-credited/ImageCredited.tsx
- src/stories/Library/medias/Medias.stories.tsx
- src/stories/Library/medias/Medias.tsx
- src/stories/Library/medias/medias.scss
- src/styles/scss/tools/variables.layout.scss
https://reload.atlassian.net/browse/DDFFORM-73
> Styling for 'medias' component, supporting 1 or 2 images. DDFFORM-73

- src/styles/scss/tools/placeholder.scss
This Pull Request introduces a media query to the `%identity-placeholder` element, enabling responsive adjustments to its border width based on the viewport size.
> Add media query for border width for `%identity-placeholder`

- src/stories/Blocks/event-page/EventPage.stories.tsx
- src/stories/Library/image-credited/image-credited.scss
https://reload.atlassian.net/browse/DDFFORM-96
Reflect changes in dpl-cms where the hero image change to an aspect ratio of 4:6.
See: https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/571
> Update aspect ratio in `ImageCredited`

- src/stories/Library/link-with-icon/LinkWithIcon.tsx
- Adjustments to linkskomponent
[jira issue]([DDFFORM-97](https://reload.atlassian.net/browse/DDFFORM-97)
https://reload.atlassian.net/browse/DDFFORM-97)
Changed SVG from large to small. 
Does not include any changes to padding on element for mobile. 
> links komponent fixes

- src/styles/scss/tools/placeholder.scss
https://reload.atlassian.net/browse/DDFFORM-100
This pull request refactors the border color of the `%identity-placeholder`. The border color is updated to use the correct variable, allowing for easier customization.
> Refactor `%identity-placeholder` border color

- src/stories/Library/logo/logo.scss
https://reload.atlassian.net/browse/DDFFORM-101
This pull request adds a responsive design to the `.logo` image, hiding it on small screens and displaying it on larger screens.
> Implement responsive design for `.logo` image to hide on small screens.

- docs/layout-documentation.md
- src/stories/Blocks/event-list-page/event-list-page.scss
- src/stories/Library/event-list-item/event-list-item.scss
- src/stories/Library/event-list/event-list.scss
- src/stories/Library/event-paragraphs/event-paragraphs.scss
- src/stories/Library/medias/medias.scss
- src/stories/Library/rich-text/rich-text.scss
- src/styles/scss/tools/README.md
- src/styles/scss/tools/mixins.misc.scss
- src/styles/scss/tools/variables.layout.scss
- Refactor layout variables & move component specfic variables
- Initial mixins for layout-container and vertical-spacing, including variables.
- Added utility classes for layout scss.
- Added documentation and examples for the usage of layout.scss
[Jira ticket](https://reload.atlassian.net/browse/DDFFORM-123)
This PR implements a starting point for managing the layout of elements/containers and spacing between them for the project. 
Please read the commits, things should mostly be explained there. 
The documentation in the last commit is probably good to read aswell. 
Consider what you think about this as as a whole comment it. This could be anything from explicity of variables to how the mixins are included and used. 
I don't have a clear idea of when/why we would need the utility …
> DDFFORM 123

- src/stories/Library/slider/init-slider.js
> Fix pa11y issue with swiper.

- src/stories/Library/paragraph/paragraph.scss
- src/stories/Library/paragraphs/Paragraphs.tsx
- src/stories/Library/video-embed/VideoEmbed.tsx
- src/stories/Library/video-embed/video-embed.scss
Making sure all paragraphs have a .paragraph wrapper, and adding a bundle variant class, so we can e.g. remove spacing between links paragraphs.
> Remove faulty max-width on paragraphs, that should be full width.

- base.scss
- src/stories/Blocks/header/Header.tsx
- src/stories/Library/card-grid/CardGrid.stories.tsx
- src/stories/Library/card-grid/CardGrid.tsx
- src/stories/Library/card-grid/card-grid.scss
- src/stories/Library/promo-title/PromoTitle.stories.tsx
- src/stories/Library/promo-title/PromoTitle.tsx
- src/stories/Library/promo-title/promo-title.scss
- src/styles/scss/tools/placeholder.scss
- src/styles/scss/tools/variables.typography.scss
This element is a bit tricky, as the card sizes are very dependent on screen real estate. I've tried to put as much logic as possible in SCSS, so it will be plug-n-play without too much Twig/JSX logic.
> Card Grid (nyhedskomponent) element. DDFFORM-127

- src/stories/Library/date-calendar/DateCalendar.tsx
> Added default date to dateCalendar

- src/stories/Blocks/fee-list/FeeList.stories.tsx
- src/stories/Blocks/fee-list/FeeList.tsx
- src/stories/Library/Lists/fee-list/fee-list.scss
- src/styles/scss/skeleton.scss
https://reload.atlassian.net/browse/DDFLSBP-368
These changes:
* Adds top margin to the fees list to add more air to the top interface
* Adds a fee list story (**with introduced external link button**) so we can actually work with the view
> Button for paying fees in header on  /user/me/fees page

- src/stories/Library/event-description/event-description.scss
- src/stories/Library/rich-text/rich-text.scss
This pull request encompasses the refactoring of WYSIWYG (What You See Is What You Get) styles to enhance their compatibility and flexibility within our application. The primary focus has been on the `event-description` and `rich-text` components, with an eye towards future expansions.
> Refactor WYSIWYG Styles

- src/stories/Library/Lists/list-materials/list-materials.scss
https://reload.atlassian.net/browse/DDFLSBP-388
All arrows need to behave the same across the apps
https://github.com/danskernesdigitalebibliotek/dpl-design-system/assets/28546954/690a07a9-aa3a-41e7-81cc-1034ade7b979
-
> Use same arrow button behavior for list materials cards as other cards

- base.scss
- src/stories/Blocks/reservation-page/ReservationListEmptyState.tsx
- src/stories/Blocks/reservation-page/ReservationListItem.tsx
- src/stories/Blocks/reservation-page/ReservationListItemSkeleton.tsx
- src/stories/Blocks/reservation-page/ReservationPage.stories.tsx
- src/stories/Blocks/reservation-page/ReservationPage.tsx
- src/stories/Blocks/reservation-page/ReservationPageSkeleton.tsx
- src/stories/Blocks/reservation-page/reservation-page-skeleton.scss
- src/stories/Library/card-list-page/ResultPager.tsx
- src/stories/Library/pause-reservation/PauseReservation.tsx
https://reload.atlassian.net/browse/DDFLSBP-398
https://reload.atlassian.net/browse/DDFLSBP-396
This PR introduces four stories for the reservation page block.
Fixed the problem Mikkel was talking about in his PR review:
> Reservation page stories and skeleton

- base.scss
- src/stories/Library/autosuggest-material/AutosuggestMaterial.tsx
- src/stories/Library/cover/Cover.stories.tsx
- src/stories/Library/cover/Cover.tsx
- src/stories/Library/cover/CoverImage.tsx
- src/stories/Library/cover/cover.scss
- src/stories/Library/cover/types.ts
- src/stories/Library/material-header/MaterialHeader.tsx
- src/stories/Library/recommendation/Recommendation.stories.tsx
- src/stories/Library/recommendation/Recommendation.tsx
- src/stories/Library/recommendation/recommendation-skeleton.scss
- src/stories/Library/recommendation/recommendation.scss
- src/stories/Library/recommended-material/RecommendedMaterial.stories.tsx
- src/stories/Library/recommended-material/RecommendedMaterial.tsx
- src/stories/Library/recommended-material/RecommendedMaterialArgs.ts
- src/stories/Library/recommended-material/recommended-material-skeleton.scss
- src/stories/Library/recommended-material/recommended-material.scss
- src/styles/scss/tools/variables.layout.scss
- Added recommended-material component.
- Added recommendation component.
[jira issue](https://reload.atlassian.net/jira/software/c/projects/DDFFORM/boards/485?selectedIssue=DDFFORM-128)
The pr adds the design for the recommendation component & recommended material. 
See commit messages. 
material: 
Recommendation (wrapper):
The arrow is supposed to be large on mobile, as in _the size it is, when hovered_. 
For now i just made the arrow as it is, since the css does not easily support the arrow sgs being modular. This is something i would like to change later on. This isn't a detailed explanation of "why" it doesnt work easily, i'm just mentioning it in case you saw it in the review.
> DDFFORM 128 spotlight component

- .github/workflows/create-release-on-branch-changes.yml
- .github/workflows/create-release-on-tag.yml
Apparently it works better to authenticate the npm read/write with a .npmrc file.
> Add .npmrc file in release workflows

- src/stories/Library/logo/logo.scss
DDFFORM-176 DDFFORM-177
Relies on:
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/717
> Allow logos to also support images without height/width set. (E.g. SVG)

- src/stories/Library/Lists/list-description/list-description.scss
- Update fontsizes for event list description on event page.
This PR updates the font size for the list component used on an event page.
> DDFFORM 174 event info full font size

- src/stories/Library/event-list-item/event-list-item.scss
- src/stories/Library/event-list/event-list.scss
- src/stories/Library/medias/medias.scss
- src/styles/scss/tools/variables.layout.scss
- refactor "large" block width to x-large.
- Refactor eventlist Item css
This PR updates the css / layout for the event list item used on the events page.
> update event list item

- src/stories/Library/Lists/list-materials/list-materials.scss
https://reload.atlassian.net/browse/DDFLSBP-340
This PR adds drop shadown on hover for group modal items.
(hovering over the highlighted item)
-
> Add drop shadown on hover for group modal items

- src/stories/Library/nav-teaser/nav-teaser.scss
https://reload.atlassian.net/browse/DDFFORM-283
This pull request introduces a style update to the `.nav-teaser` component by adding a black color
> Add black color to `.nav-teaser` component

- src/stories/Library/card/card.scss
- src/stories/Library/nav-spot/NavSpot.tsx
- src/stories/Library/nav-spot/nav-spot.scss
- src/stories/Library/nav-spots/NavSpots.stories.tsx
- src/stories/Library/slider/init-slider.js
- src/styles/scss/tools/placeholder.scss
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/779
> Fix nav-spot, to display placeholder box when no media. DDFFORM-309

- src/stories/Blocks/header/Header.tsx
> Merge develop into 2024 8 0

- src/stories/Library/card-list-page/ResultPager.tsx
Use clsx to prevent "undefined" css class in `pager`
> Use clsx to prevent "undefined" css class in `pager`

- src/stories/Blocks/header/Header.tsx
- src/stories/Blocks/header/header.scss
https://reload.atlassian.net/browse/DDFFORM-370
This pull request refactors the styling of the clock in the header to align with the recent changes made in the dpl-cms. The related pull request for more details can be found here [825](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/825).
> Refactor styling of clock in header

- src/stories/Library/Heros/hero-link/HeroLink.tsx
- src/stories/Library/Heros/hero/HeroInner.tsx
- src/stories/Library/Heros/hero/hero.scss
https://reload.atlassian.net/browse/DDFFORM-400
https://reload.atlassian.net/browse/DDFFORM-419
This pull request includes a few minor CSS adjustments to the hero section. Please refer to the individual commits for a more detailed description of the changes
Its align with the changes in
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/860
> Ddfform 400 paragraph hero tilga link via billede

- src/stories/Library/nav-grid/NavGrid.stories.tsx
- src/stories/Library/nav-grid/NavGrid.tsx
- src/stories/Library/nav-grid/nav-grid.scss
https://reload.atlassian.net/browse/DDFFORM-396
This pull request refactors the `NavGrid` markup and CSS to consistently display a grid of three columns on screens larger than mobile devices.
In addition, I have enhanced the HTML structure to improve semantics and have refined the methods used in React for rendering HTML elements, aiming to boost readability and maintainability.
> Refactor NavGrid markup and CSS

- src/stories/Blocks/content-list-page/ContentListPage.tsx
- src/stories/Blocks/content-list-page/content-list-page.scss
https://reload.atlassian.net/browse/DDFFORM-65
This updates the design of content pages to support multiple facets. This includes visual separation and handling across mobile and desktop.
Please see the individual commits for additional commentary.
See Chromatic.
For some reason Chromatic lists a number of unrelated pages as having changed without there being any actual changes to spot. I have accepted these changes as well.
> Event facets

- src/stories/Library/date-calendar/date-calendar.scss
https://reload.atlassian.net/browse/DDFLSBP-481
Disable text selection for `.flatpickr-day` elements.
> Disable text selection for .flatpickr-day [DDFLSBP-481]

- src/stories/Blocks/favorites-list/FavoritesList.stories.tsx
- src/stories/Blocks/favorites-list/FavoritesList.tsx
https://reload.atlassian.net/browse/DDFLSBP-484
To ensure consistency, the 'Favorite Page' is retroactively added to the design system.
*
> Add Favorite Page to design system [DDFLSBP-484]

- src/stories/Library/Lists/list-materials/ListMaterials.stories.tsx
- src/stories/Library/Lists/list-materials/ListMaterials.tsx
- src/stories/Library/Lists/list-materials/list-materials.scss
- src/stories/Library/Lists/list-reservation/list-reservation.scss
- src/stories/Library/Modals/modal-loan/ModalLoan.tsx
https://reload.atlassian.net/browse/DDFLSBP-405
This PR plays around with selectable card status message placement.
Before:
After:
After on mobile:
This PR will have a sibling in dpl-react when this is merged in.
> Renewal reason should fit in on cards

- src/stories/Blocks/header/header-sticky.js
- src/styles/scss/shared.scss
This has already been reviewed, but was mistakenly merged into develop:
https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/574
> Ddfform 517 man kan zoome for langt ud pa mobil

- src/stories/Library/disclosure/Disclosure.tsx
Related to 
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/988
https://reload.atlassian.net/browse/DDFFORM-467
> Make sure accordion body has rich-text/WYSIWYG styling. DDFFORM-467

- src/stories/Blocks/header/header-sticky.js
- src/styles/scss/shared.scss
I previously had to revert commits, because i had merged them into develop by accident.
Something went completely wrong when develop was merged back into hermod-sprint-12, so they got removed again.
Long story short ^
Long story long: V
https://reload.zulipchat.com/#narrow/stream/240325-DDF/topic/develop.20troubles
> Fix broken reverts

- base.scss
- src/stories/Blocks/form/ContactForm.tsx
- src/stories/Blocks/form/form.scss
- src/stories/Library/Forms/submit-button/SubmitButton.stories.tsx
- src/stories/Library/Forms/submit-button/SubmitButton.tsx
- src/stories/Library/Forms/submit-button/submit-button.scss
- src/stories/Library/Forms/textarea/Textarea.stories.tsx
- src/stories/Library/Forms/textarea/textarea.scss
- src/styles/scss/tools/variables.typography.scss
https://reload.atlassian.net/browse/DDFLSBP-528
Scope the form elements inside of dpl-form
Some old components (input and dropdown are left unscoped)
> Scope the form elements inside of dpl-form

- src/stories/Library/opening-hours-editor/opening-hours-editor.scss
https://reload.atlassian.net/browse/DDFFORM-662
**Info**: https://reload.atlassian.net/browse/DDFFORM-632
- Implemented styles for disabled input fields
- Expanded spacing around checkbox, increased checkbox size, and updated label font style
> Enhance styling for repeated opening hours

- src/stories/Library/article-header/article-header.scss
- src/stories/Library/breadcrumb/Breadcrumb.stories.tsx
- src/stories/Library/breadcrumb/Breadcrumb.tsx
- src/stories/Library/breadcrumb/breadcrumb.scss
Look at chromatic :) 
https://616ffdab9acbf5003ad5fd2b-jiomqdzlum.chromatic.com?path=/story/library-breadcrumb--breadcrumb
https://www.figma.com/file/Zx9GrkFA3l4ISvyZD2q0Qi/Designsystem?type=design&node-id=7760-61299&mode=design&t=yVa9YIJSSytj3Ta6-4
> Breadcrumb design. DDFFORM-608

- src/stories/Library/rich-text/rich-text.scss
https://reload.atlassian.net/browse/DDFFORM-114
> Tweak rich-text list styling. DDFFORM-114

- src/stories/Library/footer-accordions/FooterAccordion.tsx
- src/stories/Library/footer-colums/FooterColumn.tsx
- src/stories/Library/nav-spot/NavSpot.tsx
- src/stories/Library/nav-teaser/NavTeaser.tsx
https://reload.atlassian.net/browse/DDFFORM-563
Following the changes introduced in https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1154/
> Restructure heading tree structure

- docs/architecture/adr-002-form-styling.md
https://reload.atlassian.net/browse/DDFLSBP-640
Write architecture decision record for form styling - .dpl-form classes
-
-
> Write architecture decision record for form styling - .dpl-form classes

- package.json
- src/stories/Library/footer-accordions/FooterAccordion.tsx
- src/stories/Library/footer-colums/FooterColumn.tsx
- src/stories/Library/nav-grid/init-nav-grid.js
- src/stories/Library/nav-spot/NavSpot.tsx
- src/stories/Library/nav-teaser/NavTeaser.tsx
- yarn.lock
Merge develop into release/brahma-17
> Merge develop into release/brahma-17

- src/stories/Blocks/header/Header.tsx
- src/stories/Blocks/header/header.scss
https://reload.atlassian.net/browse/DDFLSBP-635
Refactor advanced search button to an anchor element.
https://github.com/danskernesdigitalebibliotek/dpl-react/pull/1237
> Add anchor element.

- src/stories/Library/multiselect/Multiselect.tsx
- src/stories/Library/multiselect/multiselect.scss
https://reload.atlassian.net/browse/DDFLSBP-601
Update the Multiselect component and avoid the default blue button color on iOS.
> Update the Multiselect component [DDFLSBP-601]

- src/styles/scss/tools/variables.colors.scss
https://reload.atlassian.net/browse/DDFLSBP-660
Correct SCSS variable interpolation for CSS variable and add font-body CSS variable for use in webforms.
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1255
> Fix SCSS variables [DDFLSBP-660]

- base.scss
- src/stories/Library/paragraphs/paragraphs.scss
- src/stories/Library/simple-link/SimpleLink.stories.tsx
- src/stories/Library/simple-link/SimpleLink.tsx
- src/stories/Library/simple-link/simple-link.scss
This is a link without icons.
jira: https://reload.atlassian.net/browse/DDFFORM-827
CMS : https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1369
Create component simple links.
> Add story, component and CSS for simpleLink.

- src/stories/Library/slider/Slider.stories.tsx
- src/stories/Library/slider/Slider.tsx
- src/stories/Library/slider/slider.scss
- src/styles/scss/tools/placeholder.scss
https://reload.atlassian.net/browse/DDFFORM-917
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1364
This pull request refactors the underlined title for the `Slider` component.
Related pull request: [#1364](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1364)
> Refactored Underlined Title for `Slider`

- src/stories/Blocks/header/Header.tsx
- src/stories/Blocks/header/header.scss
https://reload.atlassian.net/browse/DDFLSBP-637
Added aria-label to the ExpandMoreIcon to reflect dpl-react changes.
This PR has a sister PR here: https://github.com/danskernesdigitalebibliotek/dpl-react/pull/1359
> Added aria-label to the ExpandMoreIcon to reflect dpl-react changes.

- src/styles/scss/reset.scss
https://reload.atlassian.net/browse/DDFFORM-831
This pull request aims to resolve the issue of unusual word wrapping by applying `hyphens: auto;` to all HTML elements. This should ensure words are split correctly with hyphens when wrapped.
I have created a copy of the Aarhus database to have more relevant content for testing. However, the Vanish URL doesn't work, so use NGINX.
https://nginx.pr-1463.dpl-cms.dplplat01.dpl.reload.dk/
> Enable automatic word hyphenation in reset.scss

- src/stories/Blocks/header/Header.tsx
- src/stories/Blocks/header/header.scss
Reverts danskernesdigitalebibliotek/dpl-design-system#701 as it was merged too soon.
> Revert "Added aria-label to the ExpandMoreIcon to reflect dpl-react changes."

- src/stories/Blocks/header/Header.tsx
- src/stories/Blocks/header/header.scss
https://reload.atlassian.net/browse/DDFFORM-852
This pull request modifies the header to display the watch on small screens instead of the favorite list and hides the text under the icons.
Additionally, I have made structural changes to the markup to align with dpl-cms and refactored the CSS for improved readability and maintenance.
https://varnish.pr-1442.dpl-cms.dplplat01.dpl.reload.dk/frontpage
> Show watch on small screens  / Refactor `header` CSS + Markup

- base.scss
- src/stories/Blocks/content-list-page/ContentListPage.tsx
- src/stories/Blocks/content-list-page/content-list-page.scss
- src/stories/Library/Modals/modal-pause/modal-pause.scss
- src/stories/Library/dropdown/dropdown.scss
- src/stories/Library/search-full-text/SearchFullText.stories.tsx
- src/stories/Library/search-full-text/SearchFullText.tsx
- src/stories/Library/search-full-text/search-full-text.scss
- src/stories/empty-view/EmptyView.stories.tsx
- src/stories/empty-view/EmptyView.tsx
- src/stories/empty-view/empty-view.scss
- src/styles/scss/tools.scss
- src/styles/scss/tools/placeholder.scss
- src/styles/scss/tools/variables.form.scss
https://reload.atlassian.net/browse/DDFFORM-66
This pull request introduces the `SearchFullText`  filter component to the `ContentListPage` for full-text search functionality in Drupal.
-Defined a global height variable for consistency across input elements.
-Updated `dropdown__select--grey` to use gray text per the design provided in Figma.
- Added a placeholder %default-focus-within to enhance form navigation by allowing tabs to move directly into inputs rather than the form container.
> DDFFORM-66 - Add `SearchFullText` filter to `ContentListPage`

- src/stories/Blocks/advanced-search/AdvancedSearch.tsx
- src/stories/Blocks/advanced-search/advanced-search.scss
- src/stories/Library/Forms/textarea/Textarea.tsx
https://reload.atlassian.net/browse/DDFHER-76
https://github.com/danskernesdigitalebibliotek/dpl-react/pull/1440
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1585
Added form elements that were previously implemented in `dpl-react`. Introduced a form wrapper to ensure appropriate spacing between elements and used the `Textarea` component for a consistent form style.
> DDFHER-76 - Add missing form elements and styling to `AdvancedSearch`

- src/stories/Library/tag/tag.scss
/?path=/story/library-tag-list--with-tags
> Add underline styling for link-tags. DDFFHER-41

- package.json
- yarn.lock
https://reload.atlassian.net/browse/DDFNEXT-203
Upgraded eslint-plugin-jsx-a11y to version 6.10.0
> Upgraded eslint-plugin-jsx-a11y

- package.json
- yarn.lock
https://reload.atlassian.net/browse/DDFBRA-157
Upgrades Typescript to its latest version
> Upgrade Typescript to version 5

- package.json
- yarn.lock
https://reload.atlassian.net/browse/DDFNEXT-506
Upgrade concurrently to latest version
> Upgrade concurrently

- .github/dependabot.yml
It should move in step with the other Storybook dependencies.
> Add main storybook dependency to Dependabot group

- .github/PULL_REQUEST_TEMPLATE.md
- .markdownlint-cli2.yaml
- docs/layout-documentation.md
- package.json
- yarn.lock
https://reload.atlassian.net/browse/DDFNEXT-202
fix: enhance PR template and update documentation.
> update: bump markdownlint-cli2 version

- base.scss
- src/stories/Library/Modals/modal.scss
- src/stories/Library/player/player.scss
https://reload.atlassian.net/browse/DDFBRA-183
https://reload.atlassian.net/browse/DDFBRA-184
Add minimal CSS for the player to be presented correctly.
> DDFBRA-183 - Add css for `Player`

- base.scss
- src/stories/Library/Modals/modal.scss
- src/stories/Library/player/player.scss
https://reload.atlassian.net/browse/DDFBRA-182
https://reload.atlassian.net/browse/DDFBRA-251
https://reload.atlassian.net/browse/DDFBRA-236
This branch will consolidate all styles related to Reader/Player functionality.
See video in this PR: https://github.com/danskernesdigitalebibliotek/dpl-react/pull/1596
https://varnish.pr-1859.dpl-cms.dplplat01.dpl.reload.dk/
> Reader / Player

- src/stories/Library/date-calendar/date-calendar.scss
Reverts danskernesdigitalebibliotek/dpl-design-system#828
I was too fast to merge this in. We need to have DDF test it first.
> Revert "Center calendar horizontally on mobile and hide box arrow"

- base.scss
- src/stories/Library/material-grid-related/material-grid-related.scss
- src/stories/Library/material-grid-related/material-grid-related.stories.tsx
- src/stories/Library/material-grid-related/material-grid-related.tsx
- src/stories/Library/material-grid/MaterialGrid.tsx
- **Update MaterialGrid structure**
- **Add MaterialGridRelated with CSS & Story**
[DDFSAL-1](https://reload.atlassian.net/browse/DDFSAL-1)
[DDFSAL-4](https://reload.atlassian.net/browse/DDFSAL-4)
[design system](https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/890)
[react repo](https://github.com/danskernesdigitalebibliotek/dpl-react/pull/1821)
[CMS](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2344)
Stories are left unaccepted until pr is reviewed. 
[DDFSAL-1]: https://reload.atlassian.net/browse/DDFSAL-1?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DDFSAL-4]: …
> DDFSAL 1 DDFSAL 4

- src/stories/Library/card-list-page/SearchResultPageData.ts
- src/stories/Library/card-list-page/facet-line.scss
- src/stories/Library/dropdown/dropdown.scss
https://reload.atlassian.net/browse/DDFBRA-645
This PR makes it so that inteligent fileters don't grow in size with more content inside their options.
-
-
> Inteligent filters shouldn't grow

- src/stories/Blocks/autosuggest/autosuggest.scss
- src/stories/Blocks/header/header.scss
Reverts danskernesdigitalebibliotek/dpl-design-system#907
We have found out that this causes problems during testing. Roll back so we can investigate.
> Revert "Add autosuggest-backdrop styling"

- package.json
- src/stories/Library/Heros/hero/hero.scss
- src/stories/Library/card/card.scss
- src/stories/Library/header-sidebar-nav/header-sidebar-nav.scss
- yarn.lock
https://reload.atlassian.net/browse/DDFSAL-235
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap
> DDFSAL-235 - Update stylelint-config-recommended-scss to `"^15.0.1"`

- .github/dependabot.yml
- .nvmrc
Update Dependabot configuration to bring it in line with https://github.com/danskernesdigitalebibliotek/dpl-docs/pull/96
Please see code comments for additional commentary.
> Dependabot update
